using CavesOfOoo.Data;
using CavesOfOoo.Diagnostics;

namespace CavesOfOoo.Core
{
    /// <summary>
    /// Gives a Spread chunk its shape — hedged rooms, crop strips, the old
    /// road, a flower meadow, gone-back scrub, or river water-meadow.
    ///
    /// <para><b>Why this exists.</b> The Spread was generated by
    /// <c>JungleBuilder</c> with the tree chance turned down, which is the
    /// retrofit the whole overhaul is meant to undo: every chunk was the
    /// same clearing with the grass moved around. This runs AFTER the base
    /// terrain and imposes a topology on it, so two adjacent Spread chunks
    /// are different <i>kinds</i> of place rather than different scatters of
    /// one place.</para>
    ///
    /// <para>Priority 2500 — after the biome terrain (1000–2000) which has
    /// carved the open ground, before connectivity (3000) which will repair
    /// anything this cuts off. That ordering is load-bearing: hedges are
    /// allowed to be inconvenient, but never to seal a chunk.</para>
    /// </summary>
    public sealed class SpreadFormationBuilder : IZoneBuilder
    {
        public string Name => "SpreadFormation";
        public int Priority => 2500;

        /// <summary>Set by tests to force a formation; otherwise derived
        /// from the zone ID.</summary>
        public Formation Override = Formation.None;

        public Formation LastFormation { get; private set; }

        public bool BuildZone(Zone zone, EntityFactory factory, System.Random rng)
        {
            if (zone == null || factory == null || rng == null) return true;

            Formation formation = Override != Formation.None
                ? Override
                : FormationSelector.For(BiomeType.Spread, zone.ZoneID);
            LastFormation = formation;

            switch (formation)
            {
                case Formation.Hedgerow: Hedgerow(zone, factory, rng); break;
                case Formation.FieldStrips: FieldStrips(zone, factory, rng); break;
                case Formation.OldRoad: OldRoad(zone, factory, rng); break;
                case Formation.FlowerMeadow: FlowerMeadow(zone, factory, rng); break;
                case Formation.Fallow: Fallow(zone, factory, rng); break;
                case Formation.RiverMeadow: RiverMeadow(zone, factory, rng); break;
            }

            Diag.Record("worldgen", "FormationApplied", payload: new
            {
                zoneID = zone.ZoneID,
                biome = nameof(BiomeType.Spread),
                formation = formation.ToString(),
            });
            return true;
        }

        // ════════════════════════════════════════════════════════
        // The formations
        // ════════════════════════════════════════════════════════

        /// <summary>Hedges cut the country into rooms. The decision the
        /// player makes is which gap to go through, and what might be
        /// waiting in the next room.</summary>
        private static void Hedgerow(Zone zone, EntityFactory factory, System.Random rng)
        {
            // Four to six lines, roughly half of them partial-length. Two
            // full-width bands across an 80x25 zone read as scratches, not
            // as rooms — you need corners for the eye to close a shape.
            int lines = 4 + rng.Next(3);
            for (int i = 0; i < lines; i++)
            {
                bool horizontal = rng.Next(2) == 0;
                int at = horizontal
                    ? 4 + rng.Next(Zone.Height - 8)
                    : 6 + rng.Next(Zone.Width - 12);

                int span = horizontal ? Zone.Width : Zone.Height;

                // Half the hedges are partial: they run from one edge and
                // stop, which is what actually makes a corner.
                int from = 1, to = span - 1;
                if (rng.Next(2) == 0)
                {
                    int cut = span / 3 + rng.Next(span / 3);
                    if (rng.Next(2) == 0) to = cut; else from = cut;
                }

                // TWO gaps, both guaranteed to land inside the RUN THAT IS
                // ACTUALLY DRAWN — [from, to), not the full span.
                //
                // This bug has now been made twice. First: one gap rolled
                // over [0, span) while drawing [1, span-1), so a gap at the
                // far end fell outside the hedge and the line came out
                // solid. Fixed — and then partial hedges were added, which
                // reintroduced exactly the same mistake in a new coordinate
                // system, because the gaps were still rolled over the full
                // span while the draw range had narrowed. Seed 6 caught it
                // both times.
                //
                // The lesson: a gap must be expressed in the same
                // coordinates as the thing it is a gap in.
                int run = to - from;
                if (run < 6) continue;          // too short to be worth a hedge
                int gapA = from + 1 + rng.Next(run - 3);
                int gapB = from + 1 + rng.Next(run - 3);

                for (int t = from; t < to; t++)
                {
                    if (t >= gapA && t < gapA + 2) continue;   // a way through
                    if (t >= gapB && t < gapB + 2) continue;   // and another
                    int x = horizontal ? t : at;
                    int y = horizontal ? at : t;
                    if (!IsOpenGround(zone, x, y)) continue;
                    BuilderSpawn.TryPlace(zone, factory, "Hedge", x, y);
                }
            }

            EnsureCrossable(zone);
        }

        /// <summary>
        /// Guarantee the chunk can still be crossed west-to-east, breaching
        /// hedges where it cannot.
        ///
        /// <para><b>Why a post-pass rather than smarter placement.</b> Every
        /// individual hedge has two gaps, and that is still not enough:
        /// crossing hedges box off corners in combinations no per-line rule
        /// sees. Seeds 6 and 36 each found one. Enumerating those cases is a
        /// losing game, so the builder checks the property it actually cares
        /// about and repairs it — hedges may be inconvenient, never
        /// sealing.</para>
        ///
        /// <para>Connectivity (priority 3000) would probably rescue this
        /// too, but a builder that relies on a later pass to clean up after
        /// it is one reorder away from shipping unreachable zones.</para>
        /// </summary>
        private static void EnsureCrossable(Zone zone)
        {
            // Bounded: each breach opens at least one cell, and there are
            // finitely many hedges.
            for (int attempt = 0; attempt < 40; attempt++)
            {
                var reached = FloodFromWest(zone, out bool crossed);
                if (crossed) return;

                // Breach the frontier hedge FURTHEST EAST.
                //
                // Taking the first one found scanning x-ascending does not
                // work: it chews through the westernmost wall cell by cell
                // and never gets anywhere, because that wall is 22 cells
                // tall and the budget runs out inside it. Seed 36 spent all
                // 40 attempts eating a single column. Picking the
                // easternmost frontier hedge drives every breach toward the
                // edge we are trying to reach, so this converges in a
                // handful of steps.
                Entity breach = null;
                int breachX = -1;
                for (int x = 1; x < Zone.Width - 1; x++)
                    for (int y = 1; y < Zone.Height - 1; y++)
                    {
                        if (!reached[x, y]) continue;
                        for (int dx = -1; dx <= 1; dx++)
                            for (int dy = -1; dy <= 1; dy++)
                            {
                                int nx = x + dx, ny = y + dy;
                                if (nx <= breachX) continue;
                                var cell = zone.GetCell(nx, ny);
                                if (cell == null) continue;
                                for (int i = 0; i < cell.Objects.Count; i++)
                                    if (cell.Objects[i] != null
                                        && cell.Objects[i].BlueprintName == "Hedge")
                                    { breach = cell.Objects[i]; breachX = nx; break; }
                            }
                    }

                if (breach == null) return;   // sealed by something not ours
                zone.RemoveEntity(breach);
            }
        }

        private static bool[,] FloodFromWest(Zone zone, out bool crossed)
        {
            var seen = new bool[Zone.Width, Zone.Height];
            var queue = new System.Collections.Generic.Queue<(int x, int y)>();
            crossed = false;

            for (int y = 1; y < Zone.Height - 1; y++)
                if (IsOpenGround(zone, 1, y)) { seen[1, y] = true; queue.Enqueue((1, y)); }

            while (queue.Count > 0)
            {
                var (x, y) = queue.Dequeue();
                if (x >= Zone.Width - 2) crossed = true;
                for (int dx = -1; dx <= 1; dx++)
                    for (int dy = -1; dy <= 1; dy++)
                    {
                        int nx = x + dx, ny = y + dy;
                        if (nx < 1 || ny < 1 || nx >= Zone.Width - 1 || ny >= Zone.Height - 1) continue;
                        if (seen[nx, ny] || !IsOpenGround(zone, nx, ny)) continue;
                        seen[nx, ny] = true;
                        queue.Enqueue((nx, ny));
                    }
            }
            return seen;
        }

        /// <summary>Worked ground: parallel crop strips with lanes between
        /// them. Reads as somebody's livelihood, which is the Spread's whole
        /// argument — this is a region that does not believe in the Tree
        /// because it is busy.</summary>
        private static void FieldStrips(Zone zone, EntityFactory factory, System.Random rng)
        {
            // Wide strips, narrow lanes, and NEAR-SOLID planting inside a
            // strip. At 72% the rows came out moth-eaten and read as noise;
            // a worked field is a solid block of crop with a clear path
            // beside it. The ragged ends are what make it look sown by hand.
            int stripWidth = 5 + rng.Next(3);
            int laneWidth = 2;
            int period = stripWidth + laneWidth;
            int phase = rng.Next(period);

            for (int x = 2; x < Zone.Width - 2; x++)
            {
                if ((x + phase) % period >= stripWidth) continue;   // the lane
                // Each strip ends a little short of the headland, and not
                // all at the same place.
                int top = 2 + rng.Next(2);
                int bottom = Zone.Height - 3 - rng.Next(2);
                for (int y = top; y < bottom; y++)
                {
                    if (!IsOpenGround(zone, x, y)) continue;
                    if (rng.Next(100) < 94)
                        BuilderSpawn.TryPlace(zone, factory, "CropRow", x, y);
                }
            }
        }

        /// <summary>The old road — straight, packed, and fast. Also the
        /// thing anything hunting a traveller already knows about.</summary>
        private static void OldRoad(Zone zone, EntityFactory factory, System.Random rng)
        {
            int y = Zone.Height / 2 + rng.Next(5) - 2;
            for (int x = 1; x < Zone.Width - 1; x++)
            {
                int wobble = y + (rng.Next(10) == 0 ? rng.Next(3) - 1 : 0);
                for (int dy = 0; dy <= 1; dy++)
                {
                    int ry = wobble + dy;
                    if (ry < 1 || ry >= Zone.Height - 1) continue;
                    ClearFor(zone, ry, x);
                    BuilderSpawn.TryPlace(zone, factory, "RoadStone", x, ry);
                }
            }
        }

        /// <summary>Flower-charm meadow — the conjured bloom canon frames
        /// as the Thinning's most intimate symptom (Lore/History/
        /// 09_Magic.md:157: "Festival-flowers wilt before noon"). The
        /// builder only SITES the flowers; how long each lives against the
        /// zone's Urqu-bleed is the flower's own business
        /// (<see cref="FlowerCharmPart"/>), so the FestivalField stamp and
        /// this formation cannot drift apart.</summary>
        private static void FlowerMeadow(Zone zone, EntityFactory factory, System.Random rng)
        {
            int cx = 12 + rng.Next(Zone.Width - 24);
            int cy = 5 + rng.Next(Zone.Height - 10);
            int radius = 4 + rng.Next(4);

            for (int x = cx - radius; x <= cx + radius; x++)
            {
                for (int y = cy - radius; y <= cy + radius; y++)
                {
                    int dx = x - cx, dy = y - cy;
                    if (dx * dx + dy * dy > radius * radius) continue;
                    if (!IsOpenGround(zone, x, y)) continue;
                    if (rng.Next(100) < 55)
                        BuilderSpawn.TryPlace(zone, factory, "FlowerField", x, y);
                }
            }
        }

        /// <summary>Gone-back ground. Scrub and volunteer growth over a
        /// field nobody works any more — the Spread's quiet reminder that
        /// people left.</summary>
        private static void Fallow(Zone zone, EntityFactory factory, System.Random rng)
        {
            for (int x = 1; x < Zone.Width - 1; x++)
            {
                for (int y = 1; y < Zone.Height - 1; y++)
                {
                    if (!IsOpenGround(zone, x, y)) continue;
                    int roll = rng.Next(100);
                    if (roll < 9) BuilderSpawn.TryPlace(zone, factory, "Bush", x, y);
                    else if (roll < 12) BuilderSpawn.TryPlace(zone, factory, "Hedge", x, y);
                }
            }
        }

        /// <summary>Water-meadow: damp ground and reeds along one edge,
        /// where the river runs or used to.</summary>
        private static void RiverMeadow(Zone zone, EntityFactory factory, System.Random rng)
        {
            bool north = rng.Next(2) == 0;
            int band = north ? 0 : Zone.Height - 1;
            int depth = 4 + rng.Next(3);

            for (int x = 1; x < Zone.Width - 1; x++)
            {
                for (int d = 0; d < depth; d++)
                {
                    int y = north ? band + d : band - d;
                    if (y < 1 || y >= Zone.Height - 1) continue;
                    if (!IsOpenGround(zone, x, y)) continue;
                    if (rng.Next(100) < 40 - d * 5)
                        BuilderSpawn.TryPlace(zone, factory, "Reeds", x, y);
                }
            }
        }

        // ════════════════════════════════════════════════════════

        /// <summary>Open, in-bounds ground with nothing solid on it. A
        /// formation decorates the space the terrain builder carved; it
        /// never digs through rock.</summary>
        private static bool IsOpenGround(Zone zone, int x, int y)
        {
            if (x < 1 || y < 1 || x >= Zone.Width - 1 || y >= Zone.Height - 1) return false;
            var cell = zone.GetCell(x, y);
            return cell != null && !cell.BlocksMovement();
        }

        /// <summary>The road is the one formation allowed to cut through:
        /// it was here before the scrub was.</summary>
        private static void ClearFor(Zone zone, int y, int x)
        {
            var cell = zone.GetCell(x, y);
            if (cell == null) return;
            for (int i = cell.Objects.Count - 1; i >= 0; i--)
            {
                var e = cell.Objects[i];
                if (e == null) continue;
                var physics = e.GetPart<PhysicsPart>();
                bool solid = e.HasTag("Solid") || (physics != null && physics.Solid);
                if (solid) zone.RemoveEntity(e);
            }
        }
    }
}
