using CavesOfOoo.Data;
using CavesOfOoo.Diagnostics;

namespace CavesOfOoo.Core
{
    /// <summary>
    /// Gives a Spread chunk its shape — hedged rooms, crop strips, the old
    /// road, a flower meadow, gone-back scrub, or river water-meadow.
    ///
    /// <para><b>Why this exists.</b> The Spread was generated by
    /// <c>JungleBuilder</c> with the tree chance turned down, which is the
    /// retrofit the whole overhaul is meant to undo: every chunk was the
    /// same clearing with the grass moved around. This runs AFTER the base
    /// terrain and imposes a topology on it, so two adjacent Spread chunks
    /// are different <i>kinds</i> of place rather than different scatters of
    /// one place.</para>
    ///
    /// <para>Priority 2500 — after the biome terrain (1000–2000) which has
    /// carved the open ground, before connectivity (3000) which will repair
    /// anything this cuts off. That ordering is load-bearing: hedges are
    /// allowed to be inconvenient, but never to seal a chunk.</para>
    /// </summary>
    public sealed class SpreadFormationBuilder : IZoneBuilder
    {
        public string Name => "SpreadFormation";
        public int Priority => 2500;

        /// <summary>Set by tests to force a formation; otherwise derived
        /// from the zone ID.</summary>
        public Formation Override = Formation.None;

        public Formation LastFormation { get; private set; }

        public bool BuildZone(Zone zone, EntityFactory factory, System.Random rng)
        {
            if (zone == null || factory == null || rng == null) return true;

            Formation formation = Override != Formation.None
                ? Override
                : FormationSelector.For(BiomeType.Spread, zone.ZoneID);
            LastFormation = formation;

            switch (formation)
            {
                case Formation.Hedgerow: Hedgerow(zone, factory, rng); break;
                case Formation.FieldStrips: FieldStrips(zone, factory, rng); break;
                case Formation.OldRoad: OldRoad(zone, factory, rng); break;
                case Formation.FlowerMeadow: FlowerMeadow(zone, factory, rng); break;
                case Formation.Fallow: Fallow(zone, factory, rng); break;
                case Formation.RiverMeadow: RiverMeadow(zone, factory, rng); break;
            }

            Diag.Record("worldgen", "FormationApplied", payload: new
            {
                zoneID = zone.ZoneID,
                biome = nameof(BiomeType.Spread),
                formation = formation.ToString(),
            });
            return true;
        }

        // ════════════════════════════════════════════════════════
        // The formations
        // ════════════════════════════════════════════════════════

        /// <summary>Hedges cut the country into rooms. The decision the
        /// player makes is which gap to go through, and what might be
        /// waiting in the next room.</summary>
        private static void Hedgerow(Zone zone, EntityFactory factory, System.Random rng)
        {
            // Two or three long hedges with deliberate gaps. Gaps are wide
            // enough (2 cells) that connectivity never has to rescue us and
            // the player is never funnelled into a single choke.
            int lines = 2 + rng.Next(2);
            for (int i = 0; i < lines; i++)
            {
                bool horizontal = rng.Next(2) == 0;
                int at = horizontal
                    ? 4 + rng.Next(Zone.Height - 8)
                    : 6 + rng.Next(Zone.Width - 12);

                int span = horizontal ? Zone.Width : Zone.Height;

                // TWO gaps, both guaranteed to land INSIDE the drawn span.
                //
                // The first version rolled one gap anywhere in [0, span) while
                // drawing over [1, span-1) — so a gap rolled at the far end
                // fell outside the hedge entirely and the line came out
                // solid. Seed 6 built a sealed chunk. Two gaps also reads
                // better: a real hedgerow has more than one gate.
                int lo = 2, hi = span - 4;
                int gapA = lo + rng.Next(hi - lo);
                int gapB = lo + rng.Next(hi - lo);

                for (int t = 1; t < span - 1; t++)
                {
                    if (t >= gapA && t < gapA + 2) continue;   // a way through
                    if (t >= gapB && t < gapB + 2) continue;   // and another
                    int x = horizontal ? t : at;
                    int y = horizontal ? at : t;
                    if (!IsOpenGround(zone, x, y)) continue;
                    BuilderSpawn.TryPlace(zone, factory, "Hedge", x, y);
                }
            }
        }

        /// <summary>Worked ground: parallel crop strips with lanes between
        /// them. Reads as somebody's livelihood, which is the Spread's whole
        /// argument — this is a region that does not believe in the Tree
        /// because it is busy.</summary>
        private static void FieldStrips(Zone zone, EntityFactory factory, System.Random rng)
        {
            int stripWidth = 3 + rng.Next(3);
            for (int x = 2; x < Zone.Width - 2; x++)
            {
                bool lane = (x / stripWidth) % 2 == 0;
                if (lane) continue;
                for (int y = 2; y < Zone.Height - 2; y++)
                {
                    if (!IsOpenGround(zone, x, y)) continue;
                    if (rng.Next(100) < 72)
                        BuilderSpawn.TryPlace(zone, factory, "CropRow", x, y);
                }
            }
        }

        /// <summary>The old road — straight, packed, and fast. Also the
        /// thing anything hunting a traveller already knows about.</summary>
        private static void OldRoad(Zone zone, EntityFactory factory, System.Random rng)
        {
            int y = Zone.Height / 2 + rng.Next(5) - 2;
            for (int x = 0; x < Zone.Width; x++)
            {
                int wobble = y + (rng.Next(10) == 0 ? rng.Next(3) - 1 : 0);
                for (int dy = 0; dy <= 1; dy++)
                {
                    int ry = wobble + dy;
                    if (ry < 1 || ry >= Zone.Height - 1) continue;
                    ClearFor(zone, ry, x);
                    BuilderSpawn.TryPlace(zone, factory, "RoadStone", x, ry);
                }
            }
        }

        /// <summary>Flower-charm meadow. Mechanically inert for now — W1's
        /// charm terrain and the bleed-wilt instrument land on top of this
        /// patch, and siting it first means the later slice has somewhere to
        /// attach.</summary>
        private static void FlowerMeadow(Zone zone, EntityFactory factory, System.Random rng)
        {
            int cx = 12 + rng.Next(Zone.Width - 24);
            int cy = 5 + rng.Next(Zone.Height - 10);
            int radius = 4 + rng.Next(4);

            for (int x = cx - radius; x <= cx + radius; x++)
            {
                for (int y = cy - radius; y <= cy + radius; y++)
                {
                    int dx = x - cx, dy = y - cy;
                    if (dx * dx + dy * dy > radius * radius) continue;
                    if (!IsOpenGround(zone, x, y)) continue;
                    if (rng.Next(100) < 55)
                        BuilderSpawn.TryPlace(zone, factory, "CharmFlowers", x, y);
                }
            }
        }

        /// <summary>Gone-back ground. Scrub and volunteer growth over a
        /// field nobody works any more — the Spread's quiet reminder that
        /// people left.</summary>
        private static void Fallow(Zone zone, EntityFactory factory, System.Random rng)
        {
            for (int x = 1; x < Zone.Width - 1; x++)
            {
                for (int y = 1; y < Zone.Height - 1; y++)
                {
                    if (!IsOpenGround(zone, x, y)) continue;
                    int roll = rng.Next(100);
                    if (roll < 9) BuilderSpawn.TryPlace(zone, factory, "Bush", x, y);
                    else if (roll < 12) BuilderSpawn.TryPlace(zone, factory, "Hedge", x, y);
                }
            }
        }

        /// <summary>Water-meadow: damp ground and reeds along one edge,
        /// where the river runs or used to.</summary>
        private static void RiverMeadow(Zone zone, EntityFactory factory, System.Random rng)
        {
            bool north = rng.Next(2) == 0;
            int band = north ? 0 : Zone.Height - 1;
            int depth = 4 + rng.Next(3);

            for (int x = 1; x < Zone.Width - 1; x++)
            {
                for (int d = 0; d < depth; d++)
                {
                    int y = north ? band + d : band - d;
                    if (y < 1 || y >= Zone.Height - 1) continue;
                    if (!IsOpenGround(zone, x, y)) continue;
                    if (rng.Next(100) < 40 - d * 5)
                        BuilderSpawn.TryPlace(zone, factory, "Reeds", x, y);
                }
            }
        }

        // ════════════════════════════════════════════════════════

        /// <summary>Open, in-bounds ground with nothing solid on it. A
        /// formation decorates the space the terrain builder carved; it
        /// never digs through rock.</summary>
        private static bool IsOpenGround(Zone zone, int x, int y)
        {
            if (x < 1 || y < 1 || x >= Zone.Width - 1 || y >= Zone.Height - 1) return false;
            var cell = zone.GetCell(x, y);
            return cell != null && !cell.BlocksMovement();
        }

        /// <summary>The road is the one formation allowed to cut through:
        /// it was here before the scrub was.</summary>
        private static void ClearFor(Zone zone, int y, int x)
        {
            var cell = zone.GetCell(x, y);
            if (cell == null) return;
            for (int i = cell.Objects.Count - 1; i >= 0; i--)
            {
                var e = cell.Objects[i];
                if (e == null) continue;
                var physics = e.GetPart<PhysicsPart>();
                bool solid = e.HasTag("Solid") || (physics != null && physics.Solid);
                if (solid) zone.RemoveEntity(e);
            }
        }
    }
}
