using System;
using System.Collections.Generic;
using System.Text;

namespace CavesOfOoo.Core
{
    public enum OverwritRole { Blank, Rim }
    public enum OverwritFormation { Blank, GreenRim, DryRim, PilgrimageRim }

    /// <summary>Fresh physical surface only. Bleeds are authored W7 content,
    /// never generated by this plan. The Blank remains one flat quiet sheet.</summary>
    public sealed class OverwritCompositionPlan
    {
        public readonly string ZoneID;
        public readonly int Seed, WestY, EastY, NorthX, SouthX, OutwardX, OutwardY;
        public readonly OverwritFormation Formation;
        public OverwritRole Role => Formation == OverwritFormation.Blank ? OverwritRole.Blank : OverwritRole.Rim;
        private readonly string[,] objects = new string[Zone.Width, Zone.Height];
        private readonly bool[,] approaches = new bool[Zone.Width, Zone.Height];

        private readonly struct Scope
        {
            public readonly int X, Y, Dx, Dy;
            public readonly OverwritFormation Formation;
            public Scope(int x, int y, int dx, int dy, OverwritFormation formation)
            { X = x; Y = y; Dx = dx; Dy = dy; Formation = formation; }
            public int InwardTurns => Dx > 0 ? 3 : Dx < 0 ? 1 : Dy < 0 ? 2 : 0;
        }

        private static readonly Dictionary<string, Scope> scopes = BuildScopes();
        private static Dictionary<string, Scope> BuildScopes()
        {
            // An explicit finite pilot: a later map expansion cannot silently
            // grant composition/voxel authority to an unaudited authored place.
            var ids = new[] {
                "Overworld.0.9.0", "Overworld.1.9.0", "Overworld.2.9.0",
                "Overworld.0.10.0", "Overworld.1.10.0", "Overworld.2.10.0", "Overworld.3.10.0",
                "Overworld.0.11.0", "Overworld.1.11.0", "Overworld.3.11.0", "Overworld.4.11.0",
                "Overworld.0.12.0", "Overworld.1.12.0", "Overworld.2.12.0", "Overworld.3.12.0", "Overworld.4.12.0",
                "Overworld.0.13.0", "Overworld.1.13.0", "Overworld.2.13.0", "Overworld.3.13.0",
                "Overworld.2.14.0", "Overworld.3.14.0"
            };
            var result = new Dictionary<string, Scope>(StringComparer.Ordinal);
            var directions = new[] { (dx: 1, dy: 0), (dx: 0, dy: 1), (dx: -1, dy: 0), (dx: 0, dy: -1) };
            var neighbors = new[] { BiomeType.Spread, BiomeType.Grovelands, BiomeType.Beating };
            foreach (string id in ids)
            {
                var p = WorldMap.FromZoneID(id);
                if (WorldMapAuthoring.BiomeAt(p.x, p.y) != BiomeType.Overwrit
                    || WorldMapAuthoring.PlaceAt(p.x, p.y).HasValue || SinkholeSites.IsMouth(p.x, p.y)) continue;
                var scope = new Scope(p.x, p.y, 0, 0, OverwritFormation.Blank);
                bool found = false;
                foreach (var biome in neighbors)
                {
                    foreach (var d in directions)
                    {
                        int x = p.x + d.dx, y = p.y + d.dy;
                        if (x < 0 || y < 0 || x >= WorldMap.Width || y >= WorldMap.Height
                            || WorldMapAuthoring.BiomeAt(x, y) != biome) continue;
                        scope = new Scope(p.x, p.y, d.dx, d.dy,
                            biome == BiomeType.Spread ? OverwritFormation.PilgrimageRim
                            : biome == BiomeType.Grovelands ? OverwritFormation.GreenRim : OverwritFormation.DryRim);
                        found = true; break;
                    }
                    if (found) break;
                }
                result.Add(id, scope);
            }
            return result;
        }

        public static bool IsWildernessZone(string id) => id != null && scopes.ContainsKey(id);
        public static bool IsRimZone(string id) => id != null && scopes.TryGetValue(id, out var s) && s.Formation != OverwritFormation.Blank;
        /// <summary>Yaw in clockwise quarter-turns from local +Z/map north.
        /// Invalid/interior IDs return neutral facing. No plan or allocations.</summary>
        public static int InwardQuarterTurns(string id) => id != null && scopes.TryGetValue(id, out var s) ? s.InwardTurns : 0;

        public static OverwritCompositionPlan Create(string id, int seed)
        {
            if (id == null || !scopes.TryGetValue(id, out var scope))
                throw new ArgumentException("An ordinary Overwrit surface address is required.", nameof(id));
            return new OverwritCompositionPlan(id, seed, scope);
        }

        private OverwritCompositionPlan(string id, int seed, Scope scope)
        {
            ZoneID = id; Seed = seed; Formation = scope.Formation;
            OutwardX = scope.Dx; OutwardY = scope.Dy;
            WestY = 5 + Hash(seed, scope.X, scope.Y, 11) % 15;
            EastY = 5 + Hash(seed, scope.X + 1, scope.Y, 11) % 15;
            NorthX = 10 + Hash(seed, scope.X, scope.Y, 23) % 60;
            SouthX = 10 + Hash(seed, scope.X, scope.Y + 1, 23) % 60;
            Route(0, WestY, 40, 12); Route(79, EastY, 40, 12);
            Route(NorthX, 0, 40, 12); Route(SouthX, 24, 40, 12);
            var rng = new Random(unchecked(seed ^ FormationSelector.StableIndex(id, int.MaxValue)));
            Grow(rng);
            if (Formation == OverwritFormation.PilgrimageRim && rng.Next(100) < 35)
                PilgrimageFurniture(rng);
        }

        private void Grow(Random rng)
        {
            int target = Role == OverwritRole.Blank ? rng.Next(5, 11) : rng.Next(18, 33), placed = 0;
            for (int attempt = 0; attempt < 512 && placed < target; attempt++)
            {
                int cx = rng.Next(3, Zone.Width - 3), cy = rng.Next(2, Zone.Height - 2);
                if (Role == OverwritRole.Rim && !IsRim(cx, cy)) continue;
                int cluster = rng.Next(2, 6);
                for (int i = 0; i < cluster && placed < target; i++)
                {
                    int x = cx + rng.Next(-2, 3), y = cy + rng.Next(-1, 2);
                    if (Role == OverwritRole.Rim && !IsRim(x, y)) continue;
                    if (CanPlace(x, y)) { objects[x, y] = "OverwritNewGrowth"; placed++; }
                }
            }
        }

        private void PilgrimageFurniture(Random rng)
        {
            for (int attempt = 0; attempt < 256; attempt++)
            {
                int x = rng.Next(3, Zone.Width - 3), y = rng.Next(3, Zone.Height - 3);
                if (!IsRim(x, y) || !OpenApron(x, y)) continue;
                objects[x, y] = "OverwritPilgrimBench";
                int shift = rng.Next(4, 7) * (rng.Next(2) == 0 ? -1 : 1);
                int mx = x + (OutwardY != 0 ? shift : 0), my = y + (OutwardX != 0 ? shift : 0);
                if (IsRim(mx, my) && OpenApron(mx, my)) objects[mx, my] = "OverwritWaymarker";
                return;
            }
        }

        private bool OpenApron(int x, int y)
        {
            for (int dy = -1; dy <= 1; dy++)
                for (int dx = -1; dx <= 1; dx++)
                    if (!CanPlace(x + dx, y + dy)) return false;
            return true;
        }

        private bool CanPlace(int x, int y) => x > 1 && y > 1 && x < Zone.Width - 2 && y < Zone.Height - 2
            && !approaches[x, y] && objects[x, y] == null;
        public bool IsRim(int x, int y) => InBounds(x, y) && Role == OverwritRole.Rim
            && (OutwardX > 0 ? Zone.Width - 1 - x : OutwardX < 0 ? x : OutwardY > 0 ? Zone.Height - 1 - y : y) <= 7;
        public string ObjectAt(int x, int y) => InBounds(x, y) ? objects[x, y] : null;
        public bool IsApproach(int x, int y) => InBounds(x, y) && approaches[x, y];
        private static bool InBounds(int x, int y) => x >= 0 && y >= 0 && x < Zone.Width && y < Zone.Height;

        private void Route(int x, int y, int tx, int ty)
        {
            int steps = Math.Max(Math.Abs(tx - x), Math.Abs(ty - y));
            for (int i = 0; i <= steps; i++)
            {
                int cx = x + (int)Math.Round((tx - x) * (double)i / Math.Max(1, steps));
                int cy = y + (int)Math.Round((ty - y) * (double)i / Math.Max(1, steps));
                for (int dy = -1; dy <= 1; dy++) for (int dx = -1; dx <= 1; dx++)
                    if (InBounds(cx + dx, cy + dy)) approaches[cx + dx, cy + dy] = true;
            }
        }

        private static int Hash(int seed, int x, int y, int salt)
        {
            unchecked
            {
                uint h = (uint)seed ^ 2166136261u;
                h = (h ^ (uint)x) * 16777619u; h = (h ^ (uint)y) * 16777619u;
                h = (h ^ (uint)salt) * 16777619u; return (int)(h & 0x7fffffffu);
            }
        }

        public string Signature()
        {
            var s = new StringBuilder(); s.Append(ZoneID).Append('|').Append(Formation).Append('|');
            for (int y = 0; y < Zone.Height; y++) for (int x = 0; x < Zone.Width; x++)
                if (objects[x, y] != null) s.Append(x).Append(',').Append(y).Append(':').Append(objects[x, y]).Append(';');
            return s.ToString();
        }
    }
}
