using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using CavesOfOoo.Core;
using Newtonsoft.Json.Linq;
using UnityEngine.InputSystem;

namespace CavesOfOoo.Scenarios.Custom
{
    public sealed partial class SpreadDiscoveryNativePlayer
    {
        bool _expeditionReport;
        const string ExpeditionReportIntent = "Ordinary seed64 duelist start, native map travel and walking to the existing seed keeper at11.8, explicit Nearby peat-packing mallet report, real Q/Tab notes, and F5/unsaved-step/F6 preservation of exact saved note bytes. No teleports, item grants, dialogue calls, source generation or note writes by the observer.";
        const string ExpeditionReportLimits = "One predeclared resident and report, not blind discovery, all informants, or a verified reward claim. The remembered lead remains historical and unconfirmed. The separate Sodden expedition covers the actual equipment source/use. This route does not assert the older resident crop count or whole farming sequence. Screenshots require independent review.";
        static readonly string[] ExpeditionReportChecks = { "ordinary_start", "expedition_report_source", "expedition_report_note", "expedition_report_ui", "expedition_report_saved", "expedition_report_restored", "expedition_report_finish" };

        public void InitializeExpeditionReport(ScenarioContext context)
        {
            if (string.IsNullOrWhiteSpace(SaveGameService.SaveRootOverride))
                throw new InvalidOperationException("Isolated launcher required before expedition-report bootstrap.");
            _expeditionReport = true;
            Initialize(context, connectedBuild: "duelist");
        }

        KeyValuePair<string, string>[] ExpeditionNoteBytes() => Player.Properties
            .Where(p => p.Key.StartsWith(SpreadDiscoveryNotes.Prefix, StringComparison.Ordinal)
                || p.Key.StartsWith(SpreadDiscoveryNotes.ExpeditionPrefix, StringComparison.Ordinal))
            .OrderBy(p => p.Key, StringComparer.Ordinal).ToArray();

        IEnumerator ExpeditionNotesView(string label, string note)
        {
            yield return Tap(Key.Q);
            Require(State == "QuestLogOpen" && _input.QuestLogUI.IsOpen, "real Q opens journal");
            if (!_input.QuestLogUI.NotesVisible) yield return Tap(Key.Tab);
            Require(_input.QuestLogUI.NotesVisible, "real field-notes tab");
            var lines = ((List<string>)Field(_input.QuestLogUI, "_noteLines")).ToArray();
            Require(NormalizeText(string.Join(" ", lines)).Contains(NormalizeText(note)),
                "wrapped journal retains the entire exact learned report");
            int pages = Math.Max(1, (lines.Length + 33) / 34);
            Require(pages <= 8, "bounded real notes pages");
            for (int page = 0; page < pages; page++)
            {
                Require(_input.QuestLogUI.NotesPage == page, "actual notes page index");
                yield return Capture(label + "-" + page);
                if (page + 1 < pages) yield return Tap(Key.RightArrow);
            }
            _observations.Add(new { phase = label, note, lines, pages });
            yield return CloseNormal();
        }

        IEnumerator ExpeditionReportJourney()
        {
            yield return Capture("report-00-ordinary-duelist-start");
            yield return TravelSurface("Overworld.11.8.0");
            var keeper = Zone.GetReadOnlyEntities().SingleOrDefault(e => e.BlueprintName == "SpreadSeedKeeper");
            Require(keeper != null && keeper.GetPart<ConversationPart>()?.ConversationID == "SpreadSeedKeeper_1",
                "actual committed seed keeper and authored conversation");
            yield return Approach(keeper, 160);
            Check("expedition_report_source", Zone.ZoneID == "Overworld.11.8.0"
                && ReferenceEquals(Manager.CachedZones[Zone.ZoneID], Zone)
                && SpatialQuery.Distance(Zone, Player, keeper) <= 1 && Zone.GetEntityCell(keeper)?.IsVisible == true
                && keeper.GetStatValue("Hitpoints") > 0 && !CombatSystem.IsDeathHandled(keeper));
            yield return Capture("report-01-existing-seed-keeper");

            var before = ExpeditionNoteBytes(); var beforeText = CurrentDiscoveryNotes().ToArray();
            int tick = Tick, energy = Energy, world = WorldClock.CurrentTick, drams = TradeSystem.GetDrams(Player);
            var cached = Manager.CachedZones.Keys.OrderBy(k => k, StringComparer.Ordinal).ToArray();
            string worldKey = Manager.Exploration.WorldKey;
            Require(!Manager.CachedZones.ContainsKey(SoddenDistrictPlan.WorksZoneID),
                "remote peat works have not been generated by this journey");
            yield return Chat(keeper);
            yield return Choice(c => c.Target == "Nearby");
            Require(ConversationManager.CurrentNode?.ID == "Nearby"
                && ConversationManager.VisibleChoices.Any(c => c.Text == "Remember peat-packing mallet (unconfirmed)"
                    && c.Actions?.Any(a => a.Key == SpreadDiscoveryReports.ActionName) == true),
                "actual current Nearby menu offers the exact equipment lead");
            Require(ExpeditionNoteBytes().SequenceEqual(before) && CurrentDiscoveryNotes().SequenceEqual(beforeText),
                "hearing a report alone does not write a note");
            var wrapped = ((List<string>)Field(_input.DialogueUI, "_wrappedTextLines")).ToArray();
            Require(NormalizeText(string.Join(" ", wrapped)) == NormalizeText(ConversationManager.CurrentText),
                "the actual revealed dialogue preserves its wrapped report text");
            _observations.Add(new { phase = "native-peat-report-offer", keeper = keeper.ID,
                text = ConversationManager.CurrentText, wrapped,
                choices = ConversationManager.VisibleChoices.Select(c => c.Text).ToArray() });
            yield return Capture("report-02-nearby-dialogue");
            yield return Choice(c => c.Text == "Remember peat-packing mallet (unconfirmed)"
                && c.Actions?.Any(a => a.Key == SpreadDiscoveryReports.ActionName) == true);
            var after = ExpeditionNoteBytes(); var added = after.Where(p => !before.Any(b => b.Key == p.Key)).ToArray();
            Require(added.Length == 1, "exactly one new saved report property");
            var record = JObject.Parse(added[0].Value);
            var note = CurrentDiscoveryNotes().Except(beforeText).Single();
            Check("expedition_report_note", after.Length == before.Length + 1
                && before.All(p => after.Contains(p))
                && added[0].Key == SpreadDiscoveryNotes.ExpeditionPrefix + worldKey + ":" + SoddenDistrictPlan.WorksZoneID + ":sodden-peat-works"
                && record.Value<int>("Version") == 2 && record.Value<string>("WorldKey") == worldKey
                && record.Value<string>("Subject") == "peat-mallet" && record.Value<string>("Family") == "sodden-peat-works"
                && record.Value<string>("OriginZoneID") == Zone.ZoneID && record.Value<string>("DestinationZoneID") == SoddenDistrictPlan.WorksZoneID
                && record.Value<string>("InformantID") == keeper.ID
                && note.Contains("peat-packing") && note.Contains("armor") && note.Contains("unconfirmed when heard")
                && note.Contains(keeper.GetPart<RenderPart>().DisplayName)
                && Tick == tick && Energy == energy && WorldClock.CurrentTick == world && TradeSystem.GetDrams(Player) == drams
                && Manager.CachedZones.Keys.OrderBy(k => k, StringComparer.Ordinal).SequenceEqual(cached));
            yield return CloseNormal();
            yield return ExpeditionNotesView("report-03-native-notes", note);
            Check("expedition_report_ui", ExpeditionNoteBytes().SequenceEqual(after)
                && Tick == tick && Energy == energy && WorldClock.CurrentTick == world && TradeSystem.GetDrams(Player) == drams
                && Manager.CachedZones.Keys.OrderBy(k => k, StringComparer.Ordinal).SequenceEqual(cached));

            var actor = Player; var zone = Zone; string id = Player.ID, stats = Stats(Player), gear = Gear(Player);
            int x = At.X, y = At.Y;
            yield return Tap(Key.F5); yield return Settled();
            string file = SaveFile(); _checkpointHash = HashFile(file);
            Check("expedition_report_saved", SaveGameService.GetSaveInfo("Quick").ActiveZoneID == zone.ZoneID
                && MessageLog.GetLast() == "Game saved." && !string.IsNullOrEmpty(_checkpointHash)
                && ExpeditionNoteBytes().SequenceEqual(after) && Tick == tick && Energy == energy);
            var step = Steps.Select(d => Zone.GetCell(x + d.x, y + d.y)).FirstOrDefault(c => c != null
                && Safe(Zone, c, ThreatClearance) && Zone.CanPlaceFootprint(Player, c.X, c.Y)
                && (c.X == x || c.Y == y || Zone.CanPlaceFootprint(Player, c.X, y) || Zone.CanPlaceFootprint(Player, x, c.Y)));
            Require(step != null, "real safe unsaved step exists");
            yield return StepTo(step.X, step.Y);
            Require((At.X != x || At.Y != y) && Tick > tick && HashFile(file) == _checkpointHash,
                "actual paid unsaved movement leaves checkpoint bytes untouched");
            yield return Capture("report-04-real-unsaved-step");
            yield return Reload(actor);
            Check("expedition_report_restored", Player != actor && Zone != zone && Player.ID == id && Zone.ZoneID == zone.ZoneID
                && At.X == x && At.Y == y && Tick == tick && Energy == energy && WorldClock.CurrentTick == world
                && Stats(Player) == stats && Gear(Player) == gear && TradeSystem.GetDrams(Player) == drams
                && Manager.Exploration.WorldKey == worldKey && ExpeditionNoteBytes().SequenceEqual(after)
                && CurrentDiscoveryNotes().Contains(note) && HashFile(file) == _checkpointHash
                && Manager.CachedZones.Keys.OrderBy(k => k, StringComparer.Ordinal).SequenceEqual(cached));
            yield return ExpeditionNotesView("report-05-restored-notes", note);
            Check("expedition_report_finish", State == "Normal" && !DevMode.Enabled && !Player.HasPart<BitLockerPart>()
                && !DebugInvincibility.IsEnabled(Player) && ExpeditionNoteBytes().SequenceEqual(after)
                && Tick == tick && Energy == energy && TradeSystem.GetDrams(Player) == drams);
        }
    }
}
