import hashlib,json,xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path
root=Path('/Users/steven/caves-of-ooo');base=root/'Docs/Verification/StarterSpell3D/Integration';b=base/'S3D00b-baseline';f=base/'S3D29-final-full'
def load(path):
 xml=path/'results.xml';r=ET.parse(xml).getroot();cases=r.findall('.//test-case');receipt=json.loads((path/'receipt.json').read_text());duplicates=sorted(k for k,n in Counter(x.get('fullname') for x in cases).items() if n>1)
 return {'xml':str(xml),'sha256':hashlib.sha256(xml.read_bytes()).hexdigest(),**{k:int(r.get(k)) for k in ['total','passed','failed','skipped']},'compileErrors':receipt['compileErrors']},{x.get('fullname'):x for x in cases},duplicates
bs,bc,bd=load(b);fs,fc,fd=load(f);bf={k for k,v in bc.items() if v.get('result')=='Failed'};ff={k for k,v in fc.items() if v.get('result')=='Failed'};added=sorted(set(fc)-set(bc));removed=sorted(set(bc)-set(fc));persistent=[{'fullname':k,'baselineMessage':bc[k].findtext('failure/message'),'finalMessage':fc[k].findtext('failure/message'),'sameMessage':bc[k].findtext('failure/message')==fc[k].findtext('failure/message')} for k in sorted(bf&ff)]
r={'status':'PASS' if bf==ff and all(x['sameMessage'] for x in persistent) and all(fc[k].get('result')=='Passed' for k in added) and not(removed or bd or fd or bs['compileErrors'] or fs['compileErrors']) else 'FAIL','comparison':'Exact NUnit test-case fullname sets and exact unnormalized failure/message text; no prefix, fuzzy or message-only matching.','baseline':bs,'final':fs,'newFailures':sorted(ff-bf),'baselineFailuresNoLongerFailing':sorted(bf-ff),'sameFailingNames':sorted(bf&ff),'allFailureMessagesExactlyEqual':all(x['sameMessage'] for x in persistent),'addedTestCount':len(added),'addedTestsAllPassed':all(fc[k].get('result')=='Passed' for k in added),'addedTests':added,'removedTests':removed,'duplicateFullnames':{'baseline':bd,'final':fd},'persistentFailures':persistent,'scope':'S3D29 final full-suite result compared with original pre-integration S3D00b, after ground-marker refinement and accepted S3D28c native capture. Historical S3D24/S3D25 receipts and failed S3D28/S3D28b remain unchanged.'}
(f/'baseline-comparison.json').write_text(json.dumps(r,indent=2)+'\n')
md=['# Final full-suite baseline comparison','',f'**{r["status"]}: all {len(bf&ff)} failing test names and failure messages exactly match the pre-integration S3D00b baseline.**','',f'Baseline: **{bs["passed"]:,}/{bs["total"]:,} passing**. S3D29: **{fs["passed"]:,}/{fs["total"]:,} passing**. Both have 31 failures and zero skipped cases. Both receipts record zero compiler errors.','',f'There are **{len(added)} added test cases; all pass**. New failures: **{len(ff-bf)}**. Removed baseline cases: **{len(removed)}**. No duplicate full names or ignored failures.','', 'The exact fullnames and unnormalized old/new failure messages are preserved in `baseline-comparison.json`. This closes the final tested starter-spell integration, including ground-marker refinement. S3D28c is its passing native capture; S3D24 and S3D25 remain historical source-specific receipts, and S3D28/S3D28b remain failed timing-stall receipts.','', 'Persistent baseline failures:','']+[f'- `{k}`' for k in sorted(bf&ff)]+['']
(f/'baseline-comparison.md').write_text('\n'.join(md))
print(json.dumps({k:r[k] for k in ['status','baseline','final','newFailures','baselineFailuresNoLongerFailing','allFailureMessagesExactlyEqual','addedTestCount','addedTestsAllPassed','removedTests','duplicateFullnames']},indent=2))
