using System;
using Random = System.Random;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Collections.Generic;
using CavesOfOoo.Core;
using CavesOfOoo.Data;
using NUnit.Framework;
using UnityEngine;
namespace CavesOfOoo.Tests
{
 public sealed class SpreadPredatorFeedingTests
 {
  SpreadExplorationActorTests.Scope scope;EntityFactory factory,oldCorpseFactory,oldLootFactory;Random oldLootRng;Zone z;Entity h,p,player,corpse;Part role;
  public sealed class FixedRoll:Random {readonly int roll;public FixedRoll(int n){roll=n;}public override int Next(int maxValue)=>roll;}
  public sealed class EndProbe:Part {public override string Name=>"F11FeedEnds";public int Ends;public override bool HandleEvent(GameEvent e){if(e.ID=="EndTurn")Ends++;return true;}}
  public sealed class DeathSwap:Part {public override string Name=>"F11DeathSwap";public EntityFactory Factory;public Entity Decoy;public override bool HandleEvent(GameEvent e){if(e.ID=="Died"){var zone=e.GetParameter<Zone>("Zone");var real=zone.GetReadOnlyEntities().Single(x=>x.HasTag("Corpse"));var c=zone.GetEntityCell(real);Decoy=Factory.CreateEntity("ReedbackGrazerCorpse");foreach(var kv in real.Properties)Decoy.Properties[kv.Key]=kv.Value;zone.RemoveEntity(real);Assert.True(zone.AddEntity(Decoy,c.X,c.Y));}return true;}}
  [SetUp]public void Setup()
  {role=null;corpse=null;scope=new SpreadExplorationActorTests.Scope();oldCorpseFactory=CorpsePart.Factory;oldLootFactory=LootDropSystem.Factory;oldLootRng=LootDropSystem.Rng;FactionManager.Initialize(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Data/Factions.json")));factory=new EntityFactory();factory.LoadBlueprints(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Blueprints/Objects.json")));CorpsePart.Factory=factory;LootDropSystem.Factory=null;z=new Zone("Overworld.8.8.0");h=Place("ReedbackGrazer",10,10);h.RemovePart(h.GetPart<SpreadGrazerPart>());h.BlueprintName="Furrowstalker";h.GetPart<BrainPart>().Passive=false;h.Tags["BodyNaturalAttack"]="";h.AddPart(new MeleeWeaponPart{BaseDamage="1d1+99",PenBonus=10});h.GetStat("Agility").BaseValue=100;h.GetStat("Strength").BaseValue=100;p=Place("ReedbackGrazer",11,10);p.GetPart<CorpsePart>().TestRng=new FixedRoll(69);player=Place("Player",60,20);var t=typeof(BrainPart).Assembly.GetType("CavesOfOoo.Core.SpreadPredatorPart");Assert.NotNull(t);role=(Part)Activator.CreateInstance(t);h.AddPart(role);Assert.True((bool)t.GetMethod("Configure").Invoke(role,new object[]{z,p,false}));}
  [TearDown]public void Teardown(){CorpsePart.Factory=oldCorpseFactory;LootDropSystem.Factory=oldLootFactory;LootDropSystem.Rng=oldLootRng;scope?.Dispose();}
  Entity Place(string bp,int x,int y){var e=factory.CreateEntity(bp);Assert.True(z.AddEntity(e,x,y));var b=e.GetPart<BrainPart>();if(b!=null){b.CurrentZone=z;b.Rng=new Random(1);}return e;}
  static void Turn(Entity e)=>e.FireEventAndRelease(GameEvent.New("TakeTurn"));
  object Get(string f){var field=role.GetType().GetField(f);Assert.NotNull(field,"Missing saved field "+f);return field.GetValue(role);}
  string Phase=>Get("Phase").ToString();
  Entity[] Bodies()=>z.GetReadOnlyEntities().Where(e=>e.HasTag("Corpse")).ToArray();
  void Kill(){for(int i=0;i<24&&!CombatSystem.IsDeathHandled(p);i++)Turn(h);Assert.True(CombatSystem.IsDeathHandled(p),"Fixture native strike must reach death: phase="+Phase+" hp="+p.GetStatValue("Hitpoints")+" goals="+h.GetPart<BrainPart>().GoalCount);corpse=Bodies().SingleOrDefault();}
  void Meal(){Kill();Assert.NotNull(corpse);Assert.AreEqual("Feeding",Phase);Assert.AreSame(corpse,Get("Corpse"));Assert.AreEqual(0,Get("FeedProgress"));}
  void RoundTrip(){string hi=h.ID,ci=corpse?.ID;var m=OverworldZoneManager.CreateDetached(factory,64);m.SetActiveZone(z);var state=GameSessionState.Capture("f11-feed","prototype",m,new TurnManager(),player);using(var bytes=new MemoryStream()){state.Save(new SaveWriter(bytes));bytes.Position=0;var loaded=GameSessionState.Load(new SaveReader(bytes,factory));z=loaded.ZoneManager.ActiveZone;player=loaded.Player;}h=z.GetReadOnlyEntities().Single(e=>e.ID==hi);corpse=ci==null?null:z.GetReadOnlyEntities().SingleOrDefault(e=>e.ID==ci);role=h.Parts.Single(a=>a.GetType().Name=="SpreadPredatorPart");h.GetPart<BrainPart>().CurrentZone=z;}
  [TestCase(69,true)][TestCase(70,false)]public void OwnNativeKillBindsOnlySuccessfulSeventyPercentCorpse(int roll,bool success){p.GetPart<CorpsePart>().TestRng=new FixedRoll(roll);Kill();Assert.AreEqual(70,p.GetPart<CorpsePart>().CorpseChance);Assert.AreEqual(success?1:0,Bodies().Length);Assert.AreEqual(success?"Feeding":"PreyGone",Phase);if(success){Assert.AreSame(corpse,Get("Corpse"));Assert.AreEqual(p.ID,corpse.GetProperty("SourceID"));Assert.AreEqual(h.ID,corpse.GetProperty("KillerID"));Assert.False(corpse.HasPart<HarvestablePart>());}Assert.IsNull(p.GetPart<SpreadGrazerPart>().GetType().GetField("Hunter").GetValue(p.GetPart<SpreadGrazerPart>()));}
  [Test]public void TwoPaidProgressActionsThenThirdConsumesExactOwnerWithoutRewardOrExtraPose(){Meal();int n=z.GetReadOnlyEntities().Count,hp=h.GetStatValue("Hitpoints"),poses=0;EntityVisualHooks.InteractionCallback=(a,b,zone)=>{Assert.AreSame(h,a);Assert.AreSame(corpse,b);Assert.NotNull(zone.GetEntityCell(b));poses++;};var probe=new EndProbe();h.AddPart(probe);var turns=new TurnManager();TurnManager.World=null;turns.AddEntity(h);turns.AddEntity(player);Assert.AreSame(player,turns.ProcessUntilPlayerTurn());Assert.AreEqual(1,Get("FeedProgress"));Assert.AreEqual(1,poses);Assert.AreEqual(1,probe.Ends);Assert.AreEqual(0,turns.GetEnergy(h));Assert.AreEqual(n,z.GetReadOnlyEntities().Count);turns.EndTurn(player,z);Assert.AreSame(player,turns.ProcessUntilPlayerTurn());Assert.AreEqual(2,Get("FeedProgress"));Assert.AreEqual(2,poses);Assert.NotNull(z.GetEntityCell(corpse));turns.EndTurn(player,z);Assert.AreSame(player,turns.ProcessUntilPlayerTurn());Assert.AreEqual("Fed",Phase);Assert.AreEqual(2,poses);Assert.AreEqual(3,probe.Ends);Assert.IsNull(z.GetEntityCell(corpse));Assert.AreEqual(n-1,z.GetReadOnlyEntities().Count);Assert.AreEqual(hp,h.GetStatValue("Hitpoints"));Assert.AreEqual(0,h.GetPart<InventoryPart>().Objects.Count);for(int i=0;i<4;i++)Turn(h);Assert.AreEqual(n-1,z.GetReadOnlyEntities().Count);}
  [TestCase(0)][TestCase(1)][TestCase(2)][TestCase(3)]public void ReplacementSavePreservesFiniteProgressAndExactCorpse(int progress){Meal();for(int i=0;i<progress;i++)Turn(h);var old=corpse;string id=corpse.ID;RoundTrip();Assert.AreNotSame(old,corpse);Assert.AreEqual(progress==3?"Fed":"Feeding",Phase);if(progress<3){Assert.AreEqual(id,corpse.ID);Assert.AreSame(corpse,Get("Corpse"));Assert.AreEqual(progress,Get("FeedProgress"));for(int i=progress;i<3;i++)Turn(h);}Assert.AreEqual("Fed",Phase);Assert.AreEqual(0,Bodies().Length);Turn(h);Assert.AreEqual(0,Bodies().Length);}
  [TestCase("moved")][TestCase("picked-up")][TestCase("foreign")][TestCase("source-id")][TestCase("killer-id")][TestCase("source-bp")][TestCase("replaced")]
  public void InvalidMealCancelsWithoutConsumingMatchingDecoy(string mode){Meal();var original=corpse;if(mode=="moved")Assert.True(z.MoveEntity(corpse,12,10));if(mode=="picked-up"){z.RemoveEntity(corpse);Assert.True(player.GetPart<InventoryPart>().AddObject(corpse));}if(mode=="foreign"){z.RemoveEntity(corpse);Assert.True(new Zone("other").AddEntity(corpse,11,10));}if(mode=="source-id")corpse.Properties["SourceID"]="other";if(mode=="killer-id")corpse.Properties["KillerID"]="other";if(mode=="source-bp")corpse.Properties["SourceBlueprint"]="other";if(mode=="replaced")z.RemoveEntity(corpse);var decoy=Place("ReedbackGrazerCorpse",11,10);foreach(var kv in original.Properties)decoy.Properties[kv.Key]=kv.Value;Turn(h);Assert.AreEqual("Aborted",Phase);Assert.NotNull(z.GetEntityCell(decoy));Assert.AreEqual(0,Get("FeedProgress"));}
  [Test]public void DeathCallbackReplacementWithCopiedProvenanceIsNotOriginalReceipt(){var swap=new DeathSwap{Factory=factory};p.AddPart(swap);Kill();Assert.NotNull(swap.Decoy);Assert.AreEqual("PreyGone",Phase);Assert.IsNull(Get("Corpse"));Assert.NotNull(z.GetEntityCell(swap.Decoy));}
  [TestCase(false)][TestCase(true)]public void ExternalDeathNeverClaimsMealEvenWhenKillerIDMatches(bool sameKiller){CombatSystem.HandleDeath(p,sameKiller?h:player,z);corpse=Bodies().Single();Turn(h);Assert.AreEqual("PreyGone",Phase);Assert.IsNull(Get("Corpse"));Assert.NotNull(z.GetEntityCell(corpse));}
  [TestCase("calm")][TestCase("work")][TestCase("conversation")][TestCase("party")][TestCase("hostile")]
  public void HigherPriorityStatePreemptsMeal(string mode){Meal();var b=h.GetPart<BrainPart>();if(mode=="calm")b.PushGoal(new NoFightGoal(9));if(mode=="work")b.PushGoal(new WaitGoal(9));if(mode=="conversation")b.InConversation=true;if(mode=="party"){b.SetPartyLeader(player);b.PushGoal(new FollowLeaderGoal(player));}if(mode=="hostile")Assert.True(z.MoveEntity(player,10,11));Turn(h);Assert.AreEqual(0,Get("FeedProgress"));Assert.NotNull(z.GetEntityCell(corpse));}
  [TestCase(-1)][TestCase(3)][TestCase(99)]public void MalformedProgressCannotConsumeAfterSave(int progress){Meal();role.GetType().GetField("FeedProgress").SetValue(role,progress);RoundTrip();Turn(h);Assert.AreEqual("Aborted",Phase);Assert.NotNull(z.GetEntityCell(corpse));}
  [Test]public void ProgressCallbackRemovalPreventsAnyLaterConsumptionOrReplacementClaim(){Meal();var original=corpse;EntityVisualHooks.InteractionCallback=(a,b,zone)=>zone.RemoveEntity(b);Turn(h);Assert.AreEqual(1,Get("FeedProgress"));var decoy=Place("ReedbackGrazerCorpse",11,10);foreach(var kv in original.Properties)decoy.Properties[kv.Key]=kv.Value;Turn(h);Assert.AreEqual("Aborted",Phase);Assert.NotNull(z.GetEntityCell(decoy));}
  [TestCase("calm")][TestCase("work")][TestCase("conversation")][TestCase("combat")]public void LookDoesNotClaimActiveFeedingWhenHigherBehaviorOwnsActor(string mode){Meal();var b=h.GetPart<BrainPart>();if(mode=="calm")b.PushGoal(new NoFightGoal(9));if(mode=="work")b.PushGoal(new WaitGoal(9));if(mode=="conversation")b.InConversation=true;if(mode=="combat")b.PushGoal(new KillGoal(player));Assert.IsNull(role.GetType().GetMethod("DescribeState").Invoke(role,null));Assert.AreEqual(0,Get("FeedProgress"));}
  [TestCase(69,true)][TestCase(70,false)]public void OrdinaryBeastLootRemainsIndependentAndIsNotConsumedOrRerolled(int roll,bool meal)
  {
   var field=typeof(LootTableRegistry).GetField("_byName",BindingFlags.Static|BindingFlags.NonPublic);var tables=(Dictionary<string,LootTableData>)field.GetValue(null);var saved=tables.ToArray();var initialized=typeof(LootTableRegistry).GetField("_initialized",BindingFlags.Static|BindingFlags.NonPublic);var old=initialized.GetValue(null);
   try{LootTableRegistry.Initialize(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Data/Loot/LootTables.json")));LootDropSystem.Factory=factory;LootDropSystem.Rng=new FixedRoll(0);p.GetPart<CorpsePart>().TestRng=new FixedRoll(roll);Kill();Assert.AreEqual(meal?"Feeding":"PreyGone",Phase);var drops=z.GetReadOnlyEntities().Where(e=>!e.HasTag("Creature")&&!e.HasTag("Corpse")).Select(e=>e.ID+":"+e.BlueprintName).OrderBy(x=>x).ToArray();Assert.True(drops.Any(x=>x.EndsWith(":RawMeat")));Assert.That(drops.Length,Is.GreaterThanOrEqualTo(2));for(int n=0;n<6;n++)Turn(h);CollectionAssert.AreEqual(drops,z.GetReadOnlyEntities().Where(e=>!e.HasTag("Creature")&&!e.HasTag("Corpse")).Select(e=>e.ID+":"+e.BlueprintName).OrderBy(x=>x).ToArray());Assert.AreEqual(0,Bodies().Length);}
   finally{tables.Clear();foreach(var kv in saved)tables.Add(kv.Key,kv.Value);initialized.SetValue(null,old);}
  }
  [Test]public void CreatedOwnerReceiptIsReadOnlyAndTransient(){Meal();var property=typeof(CorpsePart).GetProperty("CreatedCorpse");Assert.NotNull(property);Assert.False(property.CanWrite && property.GetSetMethod()!=null);Assert.AreSame(corpse,property.GetValue(p.GetPart<CorpsePart>()));}
  [Test]public void WorldLookReportsActualLocalPhaseWithoutMutatingOrPromisingHarvest(){string before=h.GetPart<ExaminablePart>().BuildWorldExamineLine(z,z.GetEntityCell(h));StringAssert.Contains("watch",before.ToLowerInvariant());Assert.AreEqual(24,Get("PursuitRemaining"));Meal();string feeding=h.GetPart<ExaminablePart>().BuildWorldExamineLine(z,z.GetEntityCell(h));StringAssert.Contains("feed",feeding.ToLowerInvariant());StringAssert.DoesNotContain("harvest",feeding.ToLowerInvariant());Assert.AreEqual(0,Get("FeedProgress"));for(int i=0;i<3;i++)Turn(h);string after=h.GetPart<ExaminablePart>().BuildWorldExamineLine(z,z.GetEntityCell(h));StringAssert.Contains("finished",after.ToLowerInvariant());Assert.AreEqual("Fed",Phase);}
 }
}
