using System;
using Random = System.Random;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Collections.Generic;
using CavesOfOoo.Core;
using CavesOfOoo.Data;
using NUnit.Framework;
using UnityEngine;
namespace CavesOfOoo.Tests
{
 public sealed class SpreadPredatorStage1Tests
 {
  SpreadExplorationActorTests.Scope scope;EntityFactory factory;Zone z;Entity h,p,player;Part role;
  public sealed class Probe:Part {public override string Name=>"F11ActionProbe";public int Attacks,Ends;public Entity Target;public override bool HandleEvent(GameEvent e){if(e.ID=="BeforeMeleeAttack"){Attacks++;Target=e.GetParameter<Entity>("Defender");return false;}if(e.ID=="EndTurn")Ends++;return true;}}
  [SetUp] public void Setup(){role=null;scope=new SpreadExplorationActorTests.Scope();FactionManager.Initialize(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Data/Factions.json")));factory=new EntityFactory();factory.LoadBlueprints(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Blueprints/Objects.json")));z=new Zone("Overworld.8.8.0");h=Actor(10,10);h.RemovePart(h.GetPart<SpreadGrazerPart>());h.BlueprintName="Furrowstalker";h.GetPart<BrainPart>().Passive=false;h.AddPart(new Probe());p=Actor(14,10);player=factory.CreateEntity("Player");Assert.True(z.AddEntity(player,60,20));}
  [TearDown]public void Teardown()=>scope?.Dispose();
  Entity Actor(int x,int y){var e=factory.CreateEntity("ReedbackGrazer");Assert.True(z.AddEntity(e,x,y));e.GetPart<BrainPart>().CurrentZone=z;e.GetPart<BrainPart>().Rng=new Random(1);return e;}
  void AddRole(){var t=typeof(BrainPart).Assembly.GetType("CavesOfOoo.Core.SpreadPredatorPart");Assert.NotNull(t,"Missing scoped exact-pair predator role");role=(Part)Activator.CreateInstance(t);h.AddPart(role);}
  bool Configure(){if(role==null)AddRole();return (bool)role.GetType().GetMethod("Configure").Invoke(role,new object[]{z,p});}
  object Get(string name)=>role.GetType().GetField(name).GetValue(role);
  static void Turn(Entity e)=>e.FireEventAndRelease(GameEvent.New("TakeTurn"));
  string Phase=>Get("Phase").ToString();
  void Move(Entity e,int x,int y)=>Assert.True(z.MoveEntity(e,x,y));
  void Wall(){for(int y=0;y<Zone.Height;y++){var tree=factory.CreateEntity("Tree");Assert.True(z.AddEntity(tree,13,y));}}
  string State()=>z.GetEntityPosition(h)+"|"+h.GetPart<RenderPart>().VisualFacing+"|"+Phase+"|"+Get("PursuitRemaining")+"|"+Get("SearchRemaining")+"|"+Get("LastSeenX")+","+Get("LastSeenY");
  void RoundTrip(){var hi=h.ID;var pi=p.ID;var m=OverworldZoneManager.CreateDetached(factory,64);m.SetActiveZone(z);var state=GameSessionState.Capture("f11-stage1","prototype",m,new TurnManager(),player);using(var s=new MemoryStream()){state.Save(new SaveWriter(s));s.Position=0;var restored=GameSessionState.Load(new SaveReader(s,factory));z=restored.ZoneManager.ActiveZone;player=restored.Player;}h=z.GetReadOnlyEntities().Single(e=>e.ID==hi);p=z.GetReadOnlyEntities().Single(e=>e.ID==pi);role=h.Parts.Single(a=>a.GetType().Name=="SpreadPredatorPart");h.GetPart<BrainPart>().CurrentZone=z;p.GetPart<BrainPart>().CurrentZone=z;}
  [Test]public void ExactPairAdmissionPreservesFactionAndGrazerFoodFields(){var g=p.GetPart<SpreadGrazerPart>();g.Fed=true;g.ApproachAttempts=7;Assert.True(Configure());Assert.AreSame(p,Get("Prey"));Assert.AreSame(h,g.GetType().GetField("Hunter").GetValue(g));Assert.AreEqual(24,Get("PursuitRemaining"));Assert.True(g.Fed);Assert.AreEqual(7,g.ApproachAttempts);Assert.False(FactionManager.IsHostile(h,p));Assert.False(Configure());}
  [TestCase("dead")][TestCase("foreign")][TestCase("party-hunter")][TestCase("party-prey")][TestCase("pet")][TestCase("service")][TestCase("work")][TestCase("wrong-prey")]
  public void InvalidPairRefusesWithoutReciprocalMutation(string mode){AddRole();if(mode=="dead")p.GetStat("Hitpoints").BaseValue=0;if(mode=="foreign"){z.RemoveEntity(p);Assert.True(new Zone("foreign").AddEntity(p,14,10));}if(mode=="party-hunter")h.GetPart<BrainPart>().SetPartyLeader(player);if(mode=="party-prey")p.GetPart<BrainPart>().SetPartyLeader(player);if(mode=="pet")p.Tags["Pet"]="";if(mode=="service")p.AddPart(new TraderPart());if(mode=="work")p.GetPart<BrainPart>().PushGoal(new WaitGoal(9));if(mode=="wrong-prey")p.BlueprintName="PetDog";Assert.False(Configure());Assert.False((bool)Get("Configured"));Assert.IsNull(Get("Prey"));}
  [TestCase(false)][TestCase(true)]public void HiddenPositionsCannotChangeSearchEvenAfterReplacementSave(bool save)
  {Assert.True(Configure());Turn(h);Assert.AreEqual((11,10),z.GetEntityPosition(h));Assert.AreEqual(14,Get("LastSeenX"));Assert.AreEqual(10,Get("LastSeenY"));Wall();Move(p,15,8);if(save)RoundTrip();var a=new List<string>();for(int i=0;i<8;i++){Turn(h);a.Add(State());Assert.False(h.GetPart<BrainPart>().HasGoal<KillGoal>());}string terminal=Phase;
   Teardown();Setup();Assert.True(Configure());Turn(h);Wall();Move(p,15,15);if(save)RoundTrip();var b=new List<string>();for(int i=0;i<8;i++){Turn(h);b.Add(State());}CollectionAssert.AreEqual(a,b);Assert.AreEqual("Escaped",terminal);Assert.AreEqual("Escaped",Phase);}
  [Test]public void BlockedVisibleHuntStopsAtGlobalBudget(){Assert.True(Configure());for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++)if(dx!=0||dy!=0){var hedge=factory.CreateEntity("Hedge");Assert.True(z.AddEntity(hedge,10+dx,10+dy));}Assert.True(AIHelpers.HasLineOfSight(z,10,10,14,10));for(int i=0;i<30;i++)Turn(h);Assert.AreEqual(0,Get("PursuitRemaining"));Assert.AreEqual("Exhausted",Phase);Assert.AreEqual((10,10),z.GetEntityPosition(h));}
  [TestCase(false)][TestCase(true)]public void HealthyPairedPreyUsesOpenSideExitWhenCardinalFlightBlocked(bool blocked){Move(h,12,10);Move(p,10,10);Assert.True(Configure());if(blocked)Assert.True(z.AddEntity(factory.CreateEntity("Tree"),9,10));Turn(p);var at=z.GetEntityPosition(p);Assert.AreNotEqual((10,10),at);Assert.That(AIHelpers.ChebyshevDistance(at.x,at.y,12,10),Is.GreaterThanOrEqualTo(3));Assert.AreEqual(10,p.GetStatValue("Hitpoints"));Assert.False(p.GetPart<BrainPart>().HasGoal<KillGoal>());}
  [TestCase(false,false)][TestCase(false,true)][TestCase(true,false)]public void DamagedHealthyPreyKeepsFlightDespiteOrdinaryOrExplicitPersonalTarget(bool playerDamage,bool explicitHostility){Move(h,12,10);Move(p,10,10);Assert.True(Configure());var source=playerDamage?player:h;if(playerDamage)Move(player,11,11);CombatSystem.ApplyDamage(p,1,source,z);Assert.AreEqual(playerDamage,p.GetPart<BrainPart>().IsPersonallyHostileTo(source),"Native retaliation is currently Player-only");if(explicitHostility)p.GetPart<BrainPart>().SetPersonallyHostile(h,false);if(playerDamage||explicitHostility)Assert.AreSame(source,p.GetPart<BrainPart>().Target);Turn(p);Assert.AreEqual(9,p.GetStatValue("Hitpoints"));Assert.AreNotEqual((10,10),z.GetEntityPosition(p));Assert.False(p.GetPart<BrainPart>().HasGoal<KillGoal>());Assert.AreEqual(0,h.GetPart<Probe>().Attacks);}
  [TestCase("calm")][TestCase("work")][TestCase("conversation")][TestCase("follow")]
  public void HigherPriorityHunterStateDoesNotSpendHuntBudget(string mode){Assert.True(Configure());var brain=h.GetPart<BrainPart>();if(mode=="calm")brain.PushGoal(new NoFightGoal(9));if(mode=="work")brain.PushGoal(new WaitGoal(9));if(mode=="conversation")brain.InConversation=true;if(mode=="follow"){brain.SetPartyLeader(player);brain.PushGoal(new FollowLeaderGoal(player));}Turn(h);Assert.AreEqual(24,Get("PursuitRemaining"));Assert.AreEqual(0,h.GetPart<Probe>().Attacks);}
  [Test]public void ImmediateOrdinaryHostileTakesPriorityOverAdjacentPrey(){Move(p,11,10);Move(player,10,11);Assert.True(Configure());Turn(h);Assert.AreEqual(1,h.GetPart<Probe>().Attacks);Assert.AreSame(player,h.GetPart<Probe>().Target);Assert.AreEqual(24,Get("PursuitRemaining"));Assert.True(h.GetPart<BrainPart>().HasGoal<KillGoal>());}
  [Test]public void LowHealthHunterDoesNotStrikeQuarry(){Move(p,11,10);Assert.True(Configure());h.GetStat("Hitpoints").BaseValue=2;Turn(h);Assert.AreEqual(0,h.GetPart<Probe>().Attacks);Assert.AreEqual("Aborted",Phase);}
  [Test]public void AdjacentQuarryReceivesOneNativeAttemptWithoutChildGoal(){Move(p,11,10);Assert.True(Configure());var turns=new TurnManager();turns.AddEntity(h);turns.AddEntity(player);Assert.AreSame(player,turns.ProcessUntilPlayerTurn());var probe=h.GetPart<Probe>();Assert.AreEqual(1,probe.Attacks);Assert.AreEqual(1,probe.Ends);Assert.AreEqual(0,turns.GetEnergy(h));Assert.AreEqual(23,Get("PursuitRemaining"));Assert.False(h.GetPart<BrainPart>().HasGoal<KillGoal>());}
  [TestCase("removed")][TestCase("dead")][TestCase("recruited")][TestCase("role-detached")]
  public void InvalidatedExactPairDoesNotAttackOrRetargetMatchingDecoy(string mode){Move(p,11,10);Assert.True(Configure());if(mode=="removed")z.RemoveEntity(p);if(mode=="dead")p.GetStat("Hitpoints").BaseValue=0;if(mode=="recruited")p.GetPart<BrainPart>().SetPartyLeader(player);if(mode=="role-detached")p.RemovePart(p.GetPart<SpreadGrazerPart>());Actor(10,11);Turn(h);Assert.AreEqual(0,h.GetPart<Probe>().Attacks);Assert.That(Phase,Is.EqualTo("Aborted").Or.EqualTo("PreyGone"));}
  [Test]public void NeverSeenPreyDoesNotRouteToDefaultCoordinate(){Assert.True(Configure());Wall();for(int i=0;i<8;i++){Turn(h);Assert.AreEqual((10,10),z.GetEntityPosition(h));Assert.False((bool)Get("HasLastSeen"));}RoundTrip();Turn(h);Assert.AreEqual((10,10),z.GetEntityPosition(h));Assert.False((bool)Get("HasLastSeen"));}
  [TestCase("Escaped")][TestCase("Aborted")]public void TerminalReciprocalStateRemainsSpentAcrossSave(string result){Assert.True(Configure());if(result=="Escaped"){Turn(h);Wall();Move(p,15,8);for(int i=0;i<8;i++)Turn(h);}else{h.GetStat("Hitpoints").BaseValue=2;Turn(h);}Assert.AreEqual(result,Phase);Assert.IsNull(p.GetPart<SpreadGrazerPart>().GetType().GetField("Hunter").GetValue(p.GetPart<SpreadGrazerPart>()));int budget=(int)Get("PursuitRemaining");RoundTrip();Assert.AreEqual(result,Phase);Assert.IsNull(p.GetPart<SpreadGrazerPart>().GetType().GetField("Hunter").GetValue(p.GetPart<SpreadGrazerPart>()));Assert.False(Configure());Turn(h);Assert.AreEqual(budget,Get("PursuitRemaining"));}
  [TestCase("PursuitRemaining",25)][TestCase("PursuitRemaining",-1)][TestCase("SearchRemaining",7)][TestCase("SearchRemaining",-1)][TestCase("HomeX",-1)][TestCase("HomeY",25)][TestCase("LastSeenX",80)][TestCase("LastSeenY",-1)]
  public void MalformedSavedBoundsAbortWithoutAction(string field,int value){Assert.True(Configure());Turn(h);role.GetType().GetField(field).SetValue(role,value);RoundTrip();var before=z.GetEntityPosition(h);Turn(h);Assert.AreEqual("Aborted",Phase);Assert.AreEqual(before,z.GetEntityPosition(h));Assert.IsNull(p.GetPart<SpreadGrazerPart>().GetType().GetField("Hunter").GetValue(p.GetPart<SpreadGrazerPart>()));}
  [Test]public void UnknownSavedPhaseAbortsWithoutAction(){Assert.True(Configure());var f=role.GetType().GetField("Phase");f.SetValue(role,Enum.ToObject(f.FieldType,99));RoundTrip();Turn(h);Assert.AreEqual("Aborted",Phase);Assert.AreEqual((10,10),z.GetEntityPosition(h));}
  [TestCase(false)][TestCase(true)]public void AdmissionAcceptsUnwiredColdBrainsButRefusesForeignZone(bool foreign){h.GetPart<BrainPart>().CurrentZone=foreign?new Zone("foreign"):null;p.GetPart<BrainPart>().CurrentZone=null;Assert.AreEqual(!foreign,Configure());if(!foreign){var b=h.GetPart<BrainPart>();b.CurrentZone=z;Assert.False((bool)role.GetType().GetMethod("IsCurrentPair",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(role,new object[]{p.GetPart<SpreadGrazerPart>(),z}),"live pair still requires both active brain contexts");}else Assert.IsNull(p.GetPart<SpreadGrazerPart>().GetType().GetField("Hunter").GetValue(p.GetPart<SpreadGrazerPart>()));}
  [TestCase(false)][TestCase(true)]public void OneRealTreeChangesInterleavedTerminationWithoutGuaranteeingDeath(bool cover)
  {
   // Synthetic geometry, real movement/combat/scheduler. Both outcomes honestly survive.
   Move(h,20,10);Move(p,24,10);Move(player,65,20);h.RemovePart(h.GetPart<Probe>());
   h.GetStat("Hitpoints").BaseValue=h.GetStat("Hitpoints").Max=12;h.GetStat("Strength").BaseValue=10;h.GetStat("Speed").BaseValue=110;
   h.Tags["BodyNaturalAttack"]="";h.AddPart(new MeleeWeaponPart{BaseDamage="1d4"});Assert.True(Configure());
   if(cover)Assert.True(z.AddEntity(factory.CreateEntity("Tree"),24,9));
   var turns=new TurnManager();TurnManager.World=null;turns.AddEntity(h);turns.AddEntity(p);turns.AddEntity(player);
   int attacks=0,paid=0;bool lostSight=false;EntityVisualHooks.AttackCallback=(a,b,zone)=>{if(a==h&&b==p)attacks++;};
   Assert.AreSame(player,turns.ProcessUntilPlayerTurn());
   while(paid<30 && Phase!="Escaped" && Phase!="Exhausted" && Phase!="Aborted" && !CombatSystem.IsDeathHandled(p))
   {var hc=z.GetEntityCell(h);var pc=z.GetEntityCell(p);lostSight|=!AIHelpers.HasLineOfSight(z,hc.X,hc.Y,pc.X,pc.Y);turns.EndTurn(player,z);paid++;Assert.AreSame(player,turns.ProcessUntilPlayerTurn());}
   Assert.AreEqual(cover?"Escaped":"Aborted",Phase);Assert.AreEqual(cover,lostSight);Assert.AreEqual(cover?6:12,paid);Assert.AreEqual(cover?70:130,turns.TickCount);
   Assert.AreEqual(0,attacks);Assert.AreEqual(10,p.GetStatValue("Hitpoints"));Assert.False(CombatSystem.IsDeathHandled(p));Assert.IsNull(p.GetPart<SpreadGrazerPart>().GetType().GetField("Hunter").GetValue(p.GetPart<SpreadGrazerPart>()));
  }
  [Test]public void AbortDoesNotMutateForeignGrazerPartBacklink(){Assert.True(Configure());var g=p.GetPart<SpreadGrazerPart>();g.GetType().GetField("FlightRemaining").SetValue(g,2);g.ParentEntity=player;Turn(h);Assert.AreEqual("Aborted",Phase);Assert.AreSame(h,g.GetType().GetField("Hunter").GetValue(g));Assert.AreEqual(2,g.GetType().GetField("FlightRemaining").GetValue(g));g.ParentEntity=p;}
  [TestCase(4,10,10)][TestCase(-1,10,10)][TestCase(2,-1,10)][TestCase(2,10,25)][TestCase(2,int.MinValue,int.MaxValue)]public void InvalidSavedFlightMemoryIsSpentWithoutMotion(int remaining,int x,int y){Assert.True(Configure());var g=p.GetPart<SpreadGrazerPart>();g.GetType().GetField("FlightRemaining").SetValue(g,remaining);g.GetType().GetField("ThreatX").SetValue(g,x);g.GetType().GetField("ThreatY").SetValue(g,y);RoundTrip();g=p.GetPart<SpreadGrazerPart>();var before=z.GetEntityPosition(p);Turn(p);Assert.AreEqual(before,z.GetEntityPosition(p));Assert.AreEqual(0,g.GetType().GetField("FlightRemaining").GetValue(g));}
  [Test]public void OrdinaryUnpairedGrazerStillFleesPlayer(){Move(p,10,10);Move(h,20,10);Move(player,12,10);Turn(p);Assert.AreEqual((9,10),z.GetEntityPosition(p));Assert.False(p.GetPart<BrainPart>().HasGoal<KillGoal>());}
 }
}
