using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using CavesOfOoo.Core;
using CavesOfOoo.Data;
using CavesOfOoo.Diagnostics;
using UnityEngine;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
namespace CavesOfOoo.Experiments
{
 public static class QuestFreeExplorationCurrent
 {
  const BindingFlags All=BindingFlags.Instance|BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic;
  [Serializable]public sealed class Count{public string blueprint;public int count;}
  [Serializable]public sealed class Item{public string id,blueprint,carriedBy,equippedBy;public int units;public float weight;public int commerceUnitValue;public long commerceStackBaseValue;public bool inInventoryList,inInventoryEquipment,inBodyEquipment;}
  [Serializable]public sealed class Owner{public string id,blueprint,displayName,glyph,color,parts;public int x,y,hp,sight;public bool renderDeclared,solid,takeable,passive,containerLocked,harvested;public string liquid;public int liquidVolume;public List<Item> contents=new List<Item>(),gear=new List<Item>();}
  [Serializable]public sealed class ZoneRow{public string id,poi,formation,condition,selected,result,disposition,error;public bool eligible,accepted,cachedBeforeRead;public int owners,layoutTrials,ripeRows,containers,creatures;public double generationMs;public string[] pipeline,rolledActors,rolledContainers;public List<Count> counts=new List<Count>();public List<Owner> relevantOwners=new List<Owner>();}
  [Serializable]public sealed class SeedReport{public int seed;public string beganUtc,endedUtc,metadataStart,actualPlacementStart,cohortSha256,error;public int cachedBeforeFreeze,cachedAfterFreeze;public bool placementMatched,complete;public QuestFreeCohort.Plan cohort;public List<ZoneRow> rows=new List<ZoneRow>();public string boundary="Native core source census only. ObservedManager uses the normal activating constructor inside the accepted fixture scope; it is not a detached manager. Exact fixture and outer registry restoration run afterward. No Play/input/render/visibility/awareness or human decisions. RNG is explicitly seeded once per seed and then advances in frozen BFS generation order; this is not normal global-RNG replay or visitation-order determinism. FreshGameStart policy placement is tested with a factory Player, not a full ordinary bootstrap. No actor turns, GetInventoryActions callbacks, stock transfers or reward grants.";}
  [Serializable]public sealed class LegacySignature{public int seed;public string id,formation,signature,sha256;}
  [Serializable]public sealed class LegacySignatures{public List<LegacySignature> entries=new List<LegacySignature>();}
  [Serializable]public sealed class RunReport{public string runId,beganUtc,endedUtc,unity,runtime,scope,readme;public bool restorationComplete;public List<string> files=new List<string>();public List<string> errors=new List<string>();}
  sealed class ObservedManager:OverworldZoneManager
  {
   internal readonly Dictionary<string,ZoneGenerationPipeline> Pipelines=new Dictionary<string,ZoneGenerationPipeline>();
   internal ObservedManager(EntityFactory factory,int seed):base(factory,seed){}
   protected override ZoneGenerationPipeline GetPipelineForZone(string id){var p=base.GetPipelineForZone(id);Pipelines[id]=p;return p;}
  }
  public static string Collect(string outputRoot)
  {
   if(Application.isPlaying)throw new InvalidOperationException("Run the source collector only while the editor is idle.");
   string directory=Path.Combine(Path.GetFullPath(outputRoot),DateTime.UtcNow.ToString("yyyyMMddTHHmmssZ")+"-"+Guid.NewGuid().ToString("N").Substring(0,8));Directory.CreateDirectory(directory);
   var report=new RunReport{runId=Path.GetFileName(directory),beganUtc=DateTime.UtcNow.ToString("O"),unity=Application.unityVersion,runtime=Environment.Version.ToString(),scope="Frozen metadata cohorts, then actual native source graphs. cachedBeforeRead labels the start graph already generated by placement validation; its generationMs is a cached lookup. No gameplay code or Assets writes.",readme="cohort files are written before GetZone. Per-seed failures are retained; no alternate source is substituted. Registry restoration uses existing accepted test scopes plus exact outer mutable registry snapshots."};
   var legacy=new LegacySignatures();foreach(int seed in new[]{1,64,1729})foreach(var formation in new[]{Formation.Hedgerow,Formation.FieldStrips,Formation.OldRoad,Formation.FlowerMeadow,Formation.Fallow,Formation.RiverMeadow}){string signature=SpreadCompositionPlan.Create("Overworld.8.4.0",seed,formation).Signature();legacy.entries.Add(new LegacySignature{seed=seed,id="Overworld.8.4.0",formation=formation.ToString(),signature=signature,sha256=HashBytes(Encoding.UTF8.GetBytes(signature))});}string legacyPath=Path.Combine(directory,"legacy-composition-signatures.json");Write(legacyPath,legacy);report.files.Add(legacyPath);
   var testAssembly=AppDomain.CurrentDomain.GetAssemblies().Single(a=>a.GetType("CavesOfOoo.Tests.DensityLootTestScope",false)!=null);
   Type scopeType=testAssembly.GetType("CavesOfOoo.Tests.DensityLootTestScope",true),dramaType=testAssembly.GetType("CavesOfOoo.Tests.SpreadBiomeCoverageTests+CensusDramaScope",true);
   var types=new[]{typeof(LootTableRegistry),typeof(FactionManager),typeof(PlayerReputation),typeof(LiquidRegistry),typeof(GasRegistry),typeof(Diag)};
   var guards=types.Select(t=>new StaticState(t)).ToArray();
   try
   {
    foreach(int seed in new[]{1,64,1729})
    {
     IDisposable scope=null,drama=null;var row=new SeedReport{seed=seed,beganUtc=DateTime.UtcNow.ToString("O")};
     try
     {
      scope=(IDisposable)Activator.CreateInstance(scopeType,true);var factory=(EntityFactory)scopeType.GetField("Factory",All).GetValue(scope);
      scopeType.GetMethod("Seed",All).Invoke(scope,new object[]{seed});
      LootTableRegistry.InitializeFromJsonSources(Resources.LoadAll<TextAsset>("Content/Data/Loot").Select(a=>a.text));
      FactionManager.Initialize(Resources.Load<TextAsset>("Content/Data/Factions").text);
      LiquidRegistry.InitializeFromJsonSources(Resources.LoadAll<TextAsset>("Content/Data/LiquidDefinitions").Select(a=>a.text));
      GasRegistry.InitializeFromJsonSources(Resources.LoadAll<TextAsset>("Content/Data/GasDefinitions").Select(a=>a.text));
      drama=(IDisposable)Activator.CreateInstance(dramaType,true);
      var manager=new ObservedManager(factory,seed);row.cachedBeforeFreeze=manager.CachedZones.Count;
      var candidates=FreshGameStart.CandidateZoneIds(manager,"");if(candidates.Length==0)throw new InvalidOperationException("No ordinary metadata start candidate.");row.metadataStart=candidates[0];var start=WorldMap.FromZoneID(row.metadataStart);var mask=new bool[20,20];for(int y=0;y<20;y++)for(int x=0;x<20;x++)mask[x,y]=manager.WorldMap.GetBiome(x,y)==BiomeType.Spread;
      row.cohort=JsonConvert.DeserializeObject<QuestFreeCohort.Plan>(File.ReadAllText("/Users/steven/caves-of-ooo/Docs/Verification/QuestFreeExploration/E0/NativeBaseline/20260928T020315Z-c231faba/seed-"+seed+"-cohort.json"));row.cachedAfterFreeze=manager.CachedZones.Count;
      if(row.cachedBeforeFreeze!=0||row.cachedAfterFreeze!=0)throw new InvalidOperationException("Metadata freeze generated a graph.");
      string cohortPath=Path.Combine(directory,"seed-"+seed+"-cohort.json");Write(cohortPath,row.cohort);row.cohortSha256=Hash(cohortPath);report.files.Add(cohortPath);
      // Validate the same physical start policy only AFTER the cohort is on disk.
      // A fallback refuses this comparison, rather than regenerating a favorable cohort.
      var player=factory.CreateEntity("Player");bool placed=FreshGameStart.TryPlace(manager,player,"",out var actual);row.actualPlacementStart=actual?.ZoneID;row.placementMatched=placed&&actual?.ZoneID==row.metadataStart;
      if(placed)actual.RemoveEntity(player);if(!row.placementMatched)throw new InvalidOperationException("Actual FreshGameStart placement differed from frozen metadata candidate; do not retarget the cohort after content inspection.");
      foreach(var node in row.cohort.nodes)
      {
       var zrow=new ZoneRow{id=node.id,formation=FormationSelector.For(BiomeType.Spread,node.id).ToString(),poi=manager.WorldMap.GetPOI(node.x,node.y)?.Name??"",eligible=manager.Exploration.Find(node.id)?.PlacementEligible==true,selected=manager.Exploration.Find(node.id)?.Family.ToString()??"None"};row.rows.Add(zrow);
       try
       {
        zrow.cachedBeforeRead=manager.CachedZones.ContainsKey(node.id);var clock=System.Diagnostics.Stopwatch.StartNew();var zone=manager.GetZone(node.id);clock.Stop();zrow.generationMs=clock.Elapsed.TotalMilliseconds;zrow.accepted=zone!=null&&manager.CachedZones.TryGetValue(node.id,out var cached)&&ReferenceEquals(zone,cached)&&zone.ZoneID==node.id;
        if(!zrow.accepted){zrow.disposition="generation-refused";continue;}
        ZoneGenerationPipeline pipeline;manager.Pipelines.TryGetValue(node.id,out pipeline);zrow.pipeline=pipeline?.Builders.Select(b=>b.Name).ToArray();
        var composer=pipeline?.Builders.OfType<SpreadExplorationBuilder>().SingleOrDefault();zrow.result=composer?.LastResult??"";zrow.layoutTrials=0;zrow.disposition=manager.Exploration.DispositionFor(node.id).ToString();
        var composition=pipeline?.Builders.OfType<SpreadCompositionBuilder>().SingleOrDefault();zrow.condition=composition?.Plan?.Condition??"not-composed";
        zrow.rolledActors=pipeline?.Builders.OfType<PopulationBuilder>().SingleOrDefault()?.SourceReceipt?.Owners.Select(e=>e.ID+":"+e.BlueprintName).ToArray()??new string[0];zrow.rolledContainers=pipeline?.Builders.OfType<ContainerBuilder>().SingleOrDefault()?.SourceReceipt?.Owners.Select(e=>e.ID+":"+e.BlueprintName).ToArray()??new string[0];
        var owners=zone.GetReadOnlyEntities().ToArray();int version=zone.EntityVersion;string tileState=zone.TileState.ToSaveString();zrow.owners=owners.Length;zrow.creatures=owners.Count(e=>e.HasTag("Creature"));zrow.containers=owners.Count(e=>e.HasPart<ContainerPart>());zrow.ripeRows=owners.Count(e=>e.GetPart<FieldHarvestPart>()?.Harvested==false);
        zrow.counts=owners.GroupBy(e=>e.BlueprintName??"<constructed>").OrderBy(g=>g.Key,StringComparer.Ordinal).Select(g=>new Count{blueprint=g.Key,count=g.Count()}).ToList();
        foreach(var e in owners)if(Relevant(e))zrow.relevantOwners.Add(Observe(zone,e));
        if(version!=zone.EntityVersion||!owners.SequenceEqual(zone.GetReadOnlyEntities())||tileState!=zone.TileState.ToSaveString())throw new InvalidOperationException("Source observation mutated zone membership/tile state.");
       }
       catch(Exception e){zrow.error=e.ToString();report.errors.Add(seed+" "+node.id+": "+e.Message);}
       Write(Path.Combine(directory,"seed-"+seed+"-partial.json"),row);
      }
      row.complete=row.cohort.complete&&row.rows.Count==row.cohort.nodes.Count&&row.rows.All(z=>z.accepted&&z.error==null);
     }
     catch(Exception e){row.error=e.ToString();report.errors.Add(seed+": "+e.Message);}
     finally{try{drama?.Dispose();}catch(Exception e){report.errors.Add("Drama restoration "+seed+": "+e);row.complete=false;}try{scope?.Dispose();}catch(Exception e){report.errors.Add("Fixture restoration "+seed+": "+e);row.complete=false;}row.endedUtc=DateTime.UtcNow.ToString("O");string path=Path.Combine(directory,"seed-"+seed+"-sources.json");Write(path,row);report.files.Add(path);}
    }
   }
   finally
   {
    report.restorationComplete=true;for(int i=guards.Length-1;i>=0;i--){try{guards[i].Dispose();}catch(Exception e){report.restorationComplete=false;report.errors.Add("Outer restoration: "+e);}}if(report.errors.Any(e=>e.StartsWith("Drama restoration",StringComparison.Ordinal)||e.StartsWith("Fixture restoration",StringComparison.Ordinal)))report.restorationComplete=false;report.endedUtc=DateTime.UtcNow.ToString("O");Write(Path.Combine(directory,"report.json"),report);
   }
   return Path.Combine(directory,"report.json");
  }
  static bool Relevant(Entity e)=>e.HasTag("Creature")||e.GetPart<PhysicsPart>()?.Takeable==true||e.HasPart<ContainerPart>()||e.HasPart<HarvestablePart>()||e.HasPart<FieldHarvestPart>()||e.HasPart<LiquidPoolPart>()||e.Parts.Any(p=>p.Name=="RegionalSignpost"||p.Name=="Door"||p.Name=="Bed"||p.Name=="Sanctuary"||p.Name=="Well"||p.Name=="Trader"||p.Name.Contains("Trap"));
  static Owner Observe(Zone zone,Entity e)
  {
   var p=zone.GetEntityPosition(e);var r=e.GetPart<RenderPart>();var physics=e.GetPart<PhysicsPart>();var brain=e.GetPart<BrainPart>();var container=e.GetPart<ContainerPart>();var liquid=e.GetPart<LiquidPoolPart>();var inv=e.GetPart<InventoryPart>();
   var o=new Owner{id=e.ID,blueprint=e.BlueprintName,displayName=r?.DisplayName,glyph=r?.RenderString,color=r?.ColorString,parts=string.Join(",",e.Parts.Select(x=>x.Name)),x=p.x,y=p.y,hp=e.GetStatValue("Hitpoints"),sight=brain?.SightRadius??0,passive=brain?.Passive??false,renderDeclared=r?.Visible??false,solid=physics?.Solid??false,takeable=physics?.Takeable??false,containerLocked=container?.IsLocked??false,harvested=e.GetPart<HarvestablePart>()?.Harvested??e.GetPart<FieldHarvestPart>()?.Harvested??false,liquid=liquid?.LiquidId,liquidVolume=liquid?.Volume??0};
   if(container?.Contents!=null)o.contents=container.Contents.Select(ObserveItem).ToList();var inventoryItems=inv?.Objects.ToArray()??new Entity[0];var equippedItems=inv?.EquippedItems.Values.ToArray()??new Entity[0];var bodyItems=e.GetPart<Body>()?.GetParts().Select(b=>b.Equipped).Where(v=>v!=null).ToArray()??new Entity[0];foreach(var item in inventoryItems.Concat(equippedItems).Concat(bodyItems).Distinct()){var observed=ObserveItem(item);observed.inInventoryList=inventoryItems.Contains(item);observed.inInventoryEquipment=equippedItems.Contains(item);observed.inBodyEquipment=bodyItems.Contains(item);o.gear.Add(observed);}return o;
  }
  static Item ObserveItem(Entity e){var p=e.GetPart<PhysicsPart>();return new Item{id=e.ID,blueprint=e.BlueprintName,units=e.GetPart<StackerPart>()?.StackCount??1,weight=p?.Weight??0,commerceUnitValue=e.GetPart<CommercePart>()?.Value??0,commerceStackBaseValue=(long)(e.GetPart<CommercePart>()?.Value??0)*(e.GetPart<StackerPart>()?.StackCount??1),carriedBy=p?.InInventory?.ID,equippedBy=p?.Equipped?.ID};}
  static void Write(string path,object obj){string json=JsonConvert.SerializeObject(obj,Formatting.Indented);var parsed=JObject.Parse(json);if(obj is SeedReport seed&&(!(parsed["rows"] is JArray rows)||rows.Count!=seed.rows.Count||seed.cohort!=null&&(!(parsed["cohort"]?["nodes"] is JArray nodes)||nodes.Count!=seed.cohort.nodes.Count)))throw new InvalidOperationException("Serialized source row/cohort loss.");if(obj is QuestFreeCohort.Plan plan&&(!(parsed["nodes"] is JArray pn)||pn.Count!=plan.nodes.Count||!(parsed["walk"] is JArray pw)||pw.Count!=plan.walk.Count))throw new InvalidOperationException("Serialized frozen cohort loss.");if(obj is LegacySignatures legacy&&(!(parsed["entries"] is JArray entries)||entries.Count!=legacy.entries.Count))throw new InvalidOperationException("Serialized legacy signatures loss.");File.WriteAllText(path,json);}
  static string Hash(string path)=>HashBytes(File.ReadAllBytes(path));
  static string HashBytes(byte[] bytes){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-","").ToLowerInvariant();}
  // Existing scopes restore saves/scene object/runtime refs; these exact outer
  // snapshots retain loaded registries and diagnostic buffers across their resets.
  sealed class StaticState:IDisposable
  {
   sealed class Entry{internal FieldInfo field;internal object value;internal Array array;internal DictionaryEntry[] dict;internal object[] items;internal MethodInfo clear,add;}
   readonly List<Entry> entries=new List<Entry>();
   internal StaticState(Type type)
   {
    foreach(var f in type.GetFields(BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic))
    {
     if(f.IsLiteral)continue;var e=new Entry{field=f,value=f.GetValue(null)};
     if(e.value is Array a)e.array=(Array)a.Clone();else if(e.value is IDictionary d){var items=new List<DictionaryEntry>();var iterator=d.GetEnumerator();while(iterator.MoveNext())items.Add(iterator.Entry);e.dict=items.ToArray();}
     else if(e.value is IEnumerable enumerable&&!(e.value is string)){var t=e.value.GetType();e.clear=t.GetMethod("Clear",Type.EmptyTypes);e.add=t.GetMethods().FirstOrDefault(m=>m.Name=="Add"&&m.GetParameters().Length==1);if(e.clear!=null&&e.add!=null)e.items=enumerable.Cast<object>().ToArray();}
     if(!f.IsInitOnly||e.array!=null||e.dict!=null||e.items!=null)entries.Add(e);
    }
   }
   public void Dispose()
   {
    foreach(var e in entries)
    {
     if(!e.field.IsInitOnly)e.field.SetValue(null,e.value);
     if(e.array!=null)Array.Copy(e.array,(Array)e.value,e.array.Length);
     else if(e.dict!=null){var d=(IDictionary)e.value;d.Clear();foreach(var p in e.dict)d.Add(p.Key,p.Value);}
     else if(e.items!=null){e.clear.Invoke(e.value,null);foreach(var i in e.items)e.add.Invoke(e.value,new[]{i});}
     if(!ReferenceEquals(e.value,e.field.GetValue(null))&&!Equals(e.value,e.field.GetValue(null)))throw new InvalidOperationException("Static restore mismatch: "+e.field.DeclaringType+"."+e.field.Name);
    }
   }
  }
 }
}
