using System;
using System.IO;
using System.Linq;
using System.Reflection;
using CavesOfOoo.Core;
using CavesOfOoo.Diagnostics;
using NUnit.Framework;

namespace CavesOfOoo.Tests
{
 public sealed class ConnectivityProgressTests
 {
  [Serializable] private sealed class CapturedSource{public string zone;public CapturedOwner[] owners;}
  [Serializable] private sealed class CapturedOwner{public string blueprint;public int x,y;}
  DensityLootTestScope scope;
  [SetUp]public void Setup(){scope=new DensityLootTestScope();Diag.SetChannel("worldgen",true);}
  [TearDown]public void Cleanup(){scope.Dispose();}
  sealed class BoundedRandom:Random{int calls;public BoundedRandom():base(64){}public override int Next(int max){if(++calls>2048)throw new InvalidOperationException("Connectivity failed to make finite progress before the test RNG budget.");return base.Next(max);}public override int Next(int min,int max){if(++calls>2048)throw new InvalidOperationException("Connectivity failed to make finite progress before the test RNG budget.");return base.Next(min,max);}}
  static void Clear(ConnectivityBuilder b,Zone z,CavesOfOoo.Data.EntityFactory f,int x,int y)=>typeof(ConnectivityBuilder).GetMethod("ClearAndFloor",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(b,new object[]{z,f,x,y});
  [TestCase("Hedge")][TestCase("Wall")][TestCase("Tree")]
  public void RealGenerationBlockersBecomePassableWithoutDuplicateFloor(string bp){var z=new Zone("clear");var ground=scope.Factory.CreateEntity("Grass");z.AddEntity(ground,10,10);var e=scope.Factory.CreateEntity(bp);z.AddEntity(e,10,10);Assert.True(z.GetCell(10,10).BlocksMovement());Clear(new ConnectivityBuilder(),z,scope.Factory,10,10);Assert.False(z.GetCell(10,10).BlocksMovement());Assert.IsNull(z.GetEntityCell(e));Assert.AreSame(ground,z.GetCell(10,10).Objects.Single());}
  [Test]public void HarmlessPhysicsOnlyOwnerIsPreserved(){var z=new Zone("clear");var e=new Entity();e.AddPart(new PhysicsPart{Solid=false});z.AddEntity(e,10,10);Clear(new ConnectivityBuilder(),z,scope.Factory,10,10);Assert.AreSame(e,z.GetCell(10,10).Objects.Single());}
  [TestCase(true)][TestCase(false)]public void PhysicalSecondaryBodyIsHandledOnceWithoutOrphanOccupancy(bool solid){var z=new Zone("body");var e=new Entity();e.AddPart(new PhysicsPart{Solid=solid});e.AddPart(new SpatialFootprintPart{CellsRaw="0,0;1,0"});z.AddEntity(e,9,10);Clear(new ConnectivityBuilder(),z,scope.Factory,10,10);Assert.AreEqual(!solid,z.GetEntityCell(e)!=null);Assert.AreEqual(!solid,z.GetCell(10,10).Occupants.Contains(e));Assert.AreEqual(!solid,z.GetCell(9,10).Occupants.Contains(e));}
  [TestCase(true)][TestCase(false)]public void ConnectivityNeverDeletesGeneratedCreatureOwners(bool solidTag){var z=new Zone("actor");var e=scope.Factory.CreateEntity("ChoirTendril");if(solidTag)e.SetTag("Solid");z.AddEntity(e,10,10);int hp=e.GetStatValue("Hitpoints");Clear(new ConnectivityBuilder(),z,scope.Factory,10,10);Assert.AreEqual((10,10),z.GetEntityPosition(e));Assert.AreEqual(hp,e.GetStatValue("Hitpoints"));Assert.False(CombatSystem.IsDeathHandled(e));}
  [Test]public void PhysicsOnlyRegionFinishesAndConnectsRatherThanSpinning(){var z=new Zone("hedge-regions");z.ForEachCell((c,x,y)=>{if((x==1||x==3)&&y==1)z.AddEntity(scope.Factory.CreateEntity("Grass"),x,y);else z.AddEntity(scope.Factory.CreateEntity("Hedge"),x,y);});bool ok=false;Assert.DoesNotThrow(()=>ok=new ConnectivityBuilder().BuildZone(z,scope.Factory,new BoundedRandom()));Assert.True(ok);Assert.True(ConnectivityBuilder.FloodFill(z,1,1)[3,1]);}
  [Test]public void ImpassableCreaturePartitionIsFiniteLoudRejectionAndPreservesEveryOwner(){var z=new Zone("creature-wall");for(int y=0;y<Zone.Height;y++){var e=new Entity{BlueprintName="actor"};e.SetTag("Creature");e.AddPart(new PhysicsPart{Solid=true});z.AddEntity(e,2,y);}var before=z.GetReadOnlyEntities().ToArray();bool ok=true;Assert.DoesNotThrow(()=>ok=new ConnectivityBuilder().BuildZone(z,scope.Factory,new BoundedRandom()));Assert.False(ok);foreach(var e in before)Assert.NotNull(z.GetEntityCell(e));Assert.That(Diag.Snapshot(Diag.BufferCapacity).Any(e=>e.Kind=="ConnectivityRejected"&&e.PayloadJson.Contains("no-progress")),Is.True);}
  [Test]public void CapturedSeed64SpreadSourceCompletesAllNativeOwnerRegions(){var json=UnityEngine.JsonUtility.FromJson<CapturedSource>(File.ReadAllText(Path.Combine(UnityEngine.Application.dataPath,"..","Docs","Verification","DensityCompletion","SpreadBiome","connectivity-source.json")));Assert.NotNull(json);Assert.AreEqual("Overworld.8.2.0",json.zone);Assert.NotNull(json.owners);Assert.Greater(json.owners.Length,0);var z=new Zone(json.zone);foreach(var row in json.owners){var e=scope.Factory.CreateEntity(row.blueprint);Assert.NotNull(e);Assert.True(z.AddEntity(e,row.x,row.y));}bool ok=false;Assert.DoesNotThrow(()=>ok=new ConnectivityBuilder().BuildZone(z,scope.Factory,new BoundedRandom()));Assert.True(ok);var start=z.GetAllEntities().Select(e=>z.GetEntityCell(e)).First(c=>!c.BlocksMovement());var reached=ConnectivityBuilder.FloodFill(z,start.X,start.Y);z.ForEachCell((c,x,y)=>{if(!c.BlocksMovement())Assert.True(reached[x,y],"disconnected "+x+","+y);});}
  [Test]public void ProtectedEdgeRefusesInsteadOfCertifyingUnreachableTransition(){var z=new Zone("protected-edge");for(int x=0;x<Zone.Width;x++){var e=new Entity();e.SetTag("Creature");e.AddPart(new PhysicsPart{Solid=true});z.AddEntity(e,x,0);}Assert.False(new ConnectivityBuilder().BuildZone(z,scope.Factory,new BoundedRandom()));Assert.That(Diag.Snapshot(Diag.BufferCapacity).Any(e=>e.Kind=="ConnectivityRejected"&&e.PayloadJson.Contains("edge-blocked")),Is.True);Assert.AreEqual(Zone.Width,z.GetAllEntities().Count(e=>e.HasTag("Creature")));}
  [Test]public void EmptyOpenZoneSucceedsAndReportsConnected(){var z=new Zone("open");Assert.True(new ConnectivityBuilder().BuildZone(z,scope.Factory,new BoundedRandom()));Assert.That(Diag.Snapshot(Diag.BufferCapacity).Any(e=>e.Kind=="ConnectivityConnected"),Is.True);}
  [Test]public void EntirelyBlockedZoneRefusesWithDiagnostic(){var z=new Zone("blocked");z.ForEachCell((c,x,y)=>z.AddEntity(scope.Factory.CreateEntity("Hedge"),x,y));Assert.False(new ConnectivityBuilder().BuildZone(z,scope.Factory,new BoundedRandom()));Assert.That(Diag.Snapshot(Diag.BufferCapacity).Any(e=>e.Kind=="ConnectivityRejected"&&e.PayloadJson.Contains("no-passable-cell")),Is.True);}
  [TestCase("GroveSign")][TestCase("Chest")][TestCase("StairsDown")][TestCase("StairsUp")][TestCase("VillageDoor")][TestCase("Dagger")]
  public void SemanticOwnersArePreservedEvenWithPhysicalAndSolidTagBlockers(string blueprint){var z=new Zone("protected-owner");var e=scope.Factory.CreateEntity(blueprint);Assert.NotNull(e);e.GetPart<PhysicsPart>().Solid=true;e.SetTag("Solid");z.AddEntity(e,10,10);Clear(new ConnectivityBuilder(),z,scope.Factory,10,10);Assert.AreSame(e,z.GetCell(10,10).Objects.Single());}
  [TestCase("door")][TestCase("archive")][TestCase("morrowfast")]
  public void NativeClosedDoorAuthorityIsNeverUsedAsDiggableTerrain(string kind){var z=new Zone("protected-door");var e=new Entity();e.AddPart(new PhysicsPart{Solid=true});if(kind=="door")e.AddPart(new DoorPart());if(kind=="archive")e.AddPart(new SealedLibraryBarrierPart());if(kind=="morrowfast")e.AddPart(new MorrowfastDoorPart());z.AddEntity(e,10,10);Clear(new ConnectivityBuilder(),z,scope.Factory,10,10);Assert.AreSame(e,z.GetCell(10,10).Objects.Single());}
 }
}
