using System;
using System.Collections.Generic;
using System.Linq;
using CavesOfOoo.Core;
using NUnit.Framework;
namespace CavesOfOoo.Tests
{
 public sealed class DensityWorldTravellersTests
 {
  DensityLootTestScope scope;OverworldZoneManager manager;Entity player;Zone zone;string readyId;
  [SetUp]public void Setup(){scope=new DensityLootTestScope();FactionManager.Initialize();manager=OverworldZoneManager.CreateDetached(scope.Factory,718);player=scope.Factory.CreateEntity("Player");readyId=FindWinningZone();ClearMemory();zone.RemoveEntity(zone.GetReadOnlyEntities().Single(e=>e.GetProperty(WorldTravellers.OriginProperty)!=null));}
  [TearDown]public void Cleanup(){scope.Dispose();FactionManager.Reset();}
  void ClearMemory(){foreach(var k in player.IntProperties.Keys.Where(k=>k.StartsWith("Traveller")).ToArray())player.IntProperties.Remove(k);foreach(var k in player.Properties.Keys.Where(k=>k.StartsWith("Traveller")).ToArray())player.Properties.Remove(k);}
  void Attach(Zone z){if(zone?.GetEntityCell(player)!=null)zone.RemoveEntity(player);zone=z;Assert.True(zone.AddEntity(player,10,10));manager.ReplaceLoadedState(new Dictionary<string,Zone>{{zone.ZoneID,zone}},zone.ZoneID,new Dictionary<string,List<ZoneConnection>>());}
  string FindWinningZone(){for(int x=0;x<WorldMap.Width;x++)for(int y=0;y<WorldMap.Height;y++){if(WorldMapAuthoring.TierAt(x,y)>3||manager.WorldMap.GetPOI(x,y)!=null)continue;Attach(new Zone(WorldMap.ToZoneID(x,y,0)));if(WorldTravellers.OnZoneEntered(player,zone))return zone.ZoneID;}Assert.Fail("At least one eligible zone must win the bounded entry roll.");return null;}
  Entity Spawn(){Assert.True(WorldTravellers.OnZoneEntered(player,zone));return zone.GetReadOnlyEntities().Single(e=>e.GetProperty(WorldTravellers.OriginProperty)!=null);}
  [Test]public void RealMerchantHasActualStockRealRouteAndStableIdentity(){var merchant=Spawn();Assert.AreEqual("Merchant",merchant.BlueprintName);Assert.IsNotNull(merchant.GetPart<TraderPart>());Assert.Greater(merchant.GetPart<InventoryPart>().Objects.Count,0);Assert.That(merchant.ID,Does.StartWith("traveller:"));Assert.AreNotEqual(merchant.GetProperty(WorldTravellers.OriginProperty),merchant.GetProperty(WorldTravellers.DestinationProperty));string line=WorldTravellers.DescribeConversation(merchant,player,"Merchant_1","Sources","fallback");Assert.AreNotEqual("fallback",line);StringAssert.Contains("between",line);}
  [Test]public void ReentryNeverRefreshesTheSameActorsStockOrPurse(){var merchant=Spawn();var inv=merchant.GetPart<InventoryPart>();foreach(var item in inv.Objects.ToArray())inv.RemoveObject(item);TradeSystem.SetDrams(merchant,17);var id=merchant.ID;for(int i=0;i<20;i++)Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual(id,merchant.ID);Assert.AreEqual(0,inv.Objects.Count);Assert.AreEqual(17,TradeSystem.GetDrams(merchant));}
  [Test]public void DeathOrRemovalNeverRespawnsTheEncounter(){var merchant=Spawn();merchant.SetTag("_DeathHandled");zone.RemoveEntity(merchant);Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual(1,zone.GetReadOnlyEntities().Count);}
  [Test]public void SavedEntryMemoryPreventsReplayingOrRefillingEncounter(){var merchant=Spawn();var loaded=PartRoundTripHelper.RoundTripEntity(player);zone.RemoveEntity(player);player=loaded;zone.AddEntity(player,10,10);Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual(2,zone.GetReadOnlyEntities().Count);}
  [TestCase("dead")][TestCase("death-handled")][TestCase("removed")][TestCase("npc")][TestCase("foreign")][TestCase("underground")][TestCase("village")]
  public void InvalidEntryDoesNotCreateActorOrConsumeRoll(string state){if(state=="dead")player.GetStat("Hitpoints").BaseValue=0;if(state=="death-handled")player.SetTag("_DeathHandled");if(state=="removed")zone.RemoveEntity(player);if(state=="npc")player.Tags.Remove("Player");if(state=="foreign"){var fake=new Zone(zone.ZoneID);Assert.False(WorldTravellers.OnZoneEntered(player,fake));return;}if(state=="underground"){var (x,y,z)=WorldMap.FromZoneID(zone.ZoneID);Attach(new Zone(WorldMap.ToZoneID(x,y,1)));}if(state=="village"){var(x,y,z)=WorldMap.FromZoneID(zone.ZoneID);manager.WorldMap.POIs[x,y]=new PointOfInterest(POIType.Village,"test town");}Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.False(player.IntProperties.Keys.Any(k=>k.StartsWith("Traveller")));}
  [TestCase("walls")][TestCase("reserved")][TestCase("hazard")]
  public void RefusedPlacementConsumesTheRollAndCannotBeEdgeFarmed(string kind){for(int x=0;x<Zone.Width;x++)for(int y=0;y<Zone.Height;y++){if(x==10&&y==10)continue;if(kind=="reserved")zone.GenReservedCells.Add((x,y));else if(kind=="hazard")zone.TileState.WriteCoating(x,y,"acid",20);else{var wall=new Entity();wall.SetTag("Solid");zone.AddEntity(wall,x,y);}}Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.True(player.IntProperties.Keys.Any(k=>k.StartsWith("TravellerRoll:")));zone.GenReservedCells.Clear();foreach(var e in zone.GetReadOnlyEntities().ToArray())if(e!=player)zone.RemoveEntity(e);Assert.False(WorldTravellers.OnZoneEntered(player,zone));}
  [Test]public void MissingRealRoutesCannotInventVillageNames(){for(int x=0;x<WorldMap.Width;x++)for(int y=0;y<WorldMap.Height;y++)manager.WorldMap.POIs[x,y]=null;Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual(1,zone.GetReadOnlyEntities().Count);}
  [Test]public void ThreeEncounterCapSurvivesManyDistinctEntries(){Spawn();int count=1;for(int x=0;x<WorldMap.Width;x++)for(int y=0;y<WorldMap.Height;y++){if(manager.WorldMap.GetPOI(x,y)!=null||WorldMapAuthoring.TierAt(x,y)>3)continue;Attach(new Zone(WorldMap.ToZoneID(x,y,0)));if(WorldTravellers.OnZoneEntered(player,zone))count++;}Assert.AreEqual(3,count);}
  [Test]public void CreatingAStockedTravellerDoesNotConsumeOrReplaceGlobalRandom(){var rng=new ForbiddenRandom();var oldL=LoadoutPart.Rng;var oldT=TraderPart.Rng;try{LoadoutPart.Rng=TraderPart.Rng=rng;Spawn();Assert.AreSame(rng,LoadoutPart.Rng);Assert.AreSame(rng,TraderPart.Rng);}finally{LoadoutPart.Rng=oldL;TraderPart.Rng=oldT;}}
  [TestCase("dead")][TestCase("removed")][TestCase("wrong-node")][TestCase("missing-origin")]
  public void RouteTextRequiresCurrentConversationAndLiveLocalEvidence(string state){var merchant=Spawn();if(state=="dead")merchant.SetTag("_DeathHandled");if(state=="removed")zone.RemoveEntity(merchant);if(state=="missing-origin"){var(x,y,z)=WorldMap.FromZoneID(merchant.GetProperty(WorldTravellers.OriginProperty));manager.WorldMap.POIs[x,y]=null;}Assert.AreEqual("fallback",WorldTravellers.DescribeConversation(merchant,player,"Merchant_1",state=="wrong-node"?"Advice":"Sources","fallback"));}
  sealed class ForbiddenRandom:Random{public override int Next(int maxValue)=>throw new Exception("gameplay rng consumed");public override int Next(int minValue,int maxValue)=>throw new Exception("gameplay rng consumed");}
 }
}
