using System;
using System.Linq;
using CavesOfOoo.Core;
using CavesOfOoo.Diagnostics;
using NUnit.Framework;
namespace CavesOfOoo.Tests
{
 public sealed class DensitySariAdversarialTests
 {
  Entity player; Zone zone; Random oldRng; Action<string> oldCallback; bool oldChannel;
  [SetUp] public void Setup(){oldRng=LoadoutPart.Rng;oldCallback=MessageLog.OnMessage;MessageLog.OnMessage=null;oldChannel=Diag.IsChannelEnabled("event");Diag.SetChannel("event",true);player=Player();zone=AtTier(3);zone.AddEntity(player,10,10);MessageLog.Clear();}
  [TearDown]public void Cleanup(){LoadoutPart.Rng=oldRng;MessageLog.OnMessage=oldCallback;Diag.SetChannel("event",oldChannel);}
  static Entity Player(){var e=new Entity{ID="sari-adv-"+Guid.NewGuid().ToString("N")};e.SetTag("Player");e.Statistics["Hitpoints"]=new Stat{Name="Hitpoints",BaseValue=40,Max=40};return e;}
  static Zone AtTier(int tier){for(int x=0;x<20;x++)for(int y=0;y<20;y++)if(WorldMapAuthoring.TierAt(x,y)==tier)return new Zone(WorldMap.ToZoneID(x,y,0));throw new Exception("missing authored tier");}
  void MoveTo(Zone next){zone.RemoveEntity(player);zone=next;Assert.True(zone.AddEntity(player,10,10));}
  static int Heard()=>MessageLog.GetMessages().Count(s=>s.IndexOf("sari",StringComparison.OrdinalIgnoreCase)>=0);
  [Test]public void LegacyAndCanonicalZoneIdsShareOneSavedArrival(){MoveTo(AtTier(5));Assert.True(SariAmbience.OnZoneEntered(player,zone));zone.ZoneID=zone.ZoneID.Substring(0,zone.ZoneID.Length-2);Assert.False(SariAmbience.OnZoneEntered(player,zone));Assert.AreEqual(1,Heard());}
  [Test]public void MutableZoneIdInvalidatesCachedTier(){zone.ZoneID=AtTier(1).ZoneID;Assert.AreEqual(1,SariAmbience.TierFor(zone));zone.ZoneID=AtTier(5).ZoneID;Assert.AreEqual(5,SariAmbience.TierFor(zone));Assert.True(SariAmbience.OnZoneEntered(player,zone));}
  [Test]public void SaveGraphPreservesArrivalAndSpacing(){MoveTo(AtTier(5));Assert.True(SariAmbience.OnZoneEntered(player,zone));var restored=PartRoundTripHelper.RoundTripEntityViaTokenGraph(player);zone.RemoveEntity(player);Assert.True(zone.AddEntity(restored,10,10));Assert.False(SariAmbience.OnZoneEntered(restored,zone));MessageLog.Clear();for(int i=0;i<19;i++)WorldAmbience.OnPlayerTurnEnded(restored,zone);Assert.Zero(Heard());}
  [Test]public void SaveGraphContinuesExactCosmeticSequence(){for(int i=0;i<300;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);var restored=PartRoundTripHelper.RoundTripEntityViaTokenGraph(player);var other=new Zone(zone.ZoneID);other.AddEntity(restored,10,10);MessageLog.Clear();for(int i=0;i<1000;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);var expected=MessageLog.GetMessages().ToArray();MessageLog.Clear();for(int i=0;i<1000;i++)WorldAmbience.OnPlayerTurnEnded(restored,other);CollectionAssert.AreEqual(expected,MessageLog.GetMessages());Assert.Greater(expected.Length,0);}
  [Test]public void CosmeticTurnsDoNotConsumeGameplayRandomOrFireFactChanges(){LoadoutPart.Rng=new ForbiddenRandom();var brain=new BrainPart{Rng=new ForbiddenRandom()};player.AddPart(brain);var observer=new FactObserver();player.AddPart(observer);for(int i=0;i<1000;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);Assert.Greater(Heard(),0);Assert.Zero(observer.Changes);}
  [Test]public void SillGlobalStoryFactIsNeitherSetNorCleared(){var previous=NarrativeStatePart.Current;try{var narrative=new NarrativeStatePart();NarrativeStatePart.Current=narrative;narrative.SetFact("sill_sari_heard",7);MoveTo(new Zone("Overworld.10.10.0"));for(int i=0;i<100;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);Assert.Zero(Heard());Assert.AreEqual(7,narrative.GetFact("sill_sari_heard"));}finally{NarrativeStatePart.Current=previous;}}
  [TestCase(19,false)][TestCase(20,true)]public void ExactSpacingBoundaryHasARealPassingHashControl(int elapsed,bool emits){int hit=0;for(int i=0;i<3000;i++){int before=Heard();WorldAmbience.OnPlayerTurnEnded(player,zone);if(Heard()>before&&player.GetIntProperty(WorldAmbience.TurnProperty)>40){hit=player.GetIntProperty(WorldAmbience.TurnProperty);break;}}Assert.Greater(hit,40);var control=Player();var other=new Zone(zone.ZoneID);other.AddEntity(control,10,10);control.IntProperties[WorldAmbience.TurnProperty]=hit-1;control.IntProperties[WorldAmbience.LastMessageProperty]=hit-elapsed;control.IntProperties[WorldAmbience.HasMessageProperty]=1;MessageLog.Clear();WorldAmbience.OnPlayerTurnEnded(control,other);Assert.AreEqual(emits?1:0,Heard());}
  [Test]public void TierProbabilityProducesIncreasingFrequencyOverBoundedSequence(){int previous=0;foreach(int tier in new[]{3,4,5}){var p=Player();var z=AtTier(tier);z.AddEntity(p,10,10);MessageLog.Clear();for(int i=0;i<20000;i++)WorldAmbience.OnPlayerTurnEnded(p,z);int count=Heard();Assert.Greater(count,previous);previous=count;}}
  [Test]public void FirstDistinctTierFiveArrivalMayBypassThePeriodicBudgetOnce(){MoveTo(AtTier(5));Assert.True(SariAmbience.OnZoneEntered(player,zone));var parts=WorldMap.FromZoneID(zone.ZoneID);var below=new Zone(WorldMap.ToZoneID(parts.x,parts.y,1));MoveTo(below);Assert.True(SariAmbience.OnZoneEntered(player,zone));Assert.False(SariAmbience.OnZoneEntered(player,zone));Assert.AreEqual(2,Heard());}
  [Test]public void CounterWrapPreservesRecentMessageGap(){player.IntProperties[WorldAmbience.TurnProperty]=int.MaxValue;player.IntProperties[WorldAmbience.LastMessageProperty]=int.MaxValue-5;player.IntProperties[WorldAmbience.HasMessageProperty]=1;for(int i=0;i<14;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);Assert.Zero(Heard());Assert.AreEqual(13,player.GetIntProperty(WorldAmbience.TurnProperty));}
  [Test]public void MalformedNegativeLastTurnDoesNotMuteAmbienceForever(){player.IntProperties[WorldAmbience.LastMessageProperty]=-10;player.IntProperties[WorldAmbience.HasMessageProperty]=1;for(int i=0;i<2000;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);Assert.Greater(Heard(),0);Assert.GreaterOrEqual(player.GetIntProperty(WorldAmbience.LastMessageProperty),0);}
  [Test]public void ThrowingLogObserverDoesNotReplayOrAbortAmbientEmission(){MoveTo(AtTier(5));MessageLog.OnMessage=_=>throw new InvalidOperationException("presentation observer");Assert.DoesNotThrow(()=>SariAmbience.OnZoneEntered(player,zone));Assert.AreEqual(1,Heard());Assert.False(SariAmbience.OnZoneEntered(player,zone));}
  [TestCase(-1)][TestCase(5)][TestCase(int.MaxValue)]public void UnknownEndingFailsQuietly(int ending){MoveTo(AtTier(5));player.SetIntProperty(EndingSpine.EndingProperty,ending);Assert.False(SariAmbience.OnZoneEntered(player,zone));for(int i=0;i<100;i++)WorldAmbience.OnPlayerTurnEnded(player,zone);Assert.Zero(Heard());}
  [Test]public void EachPlayerOwnsTheirOwnArrivalMemory(){MoveTo(AtTier(5));Assert.True(SariAmbience.OnZoneEntered(player,zone));var other=Player();zone.AddEntity(other,11,10);Assert.True(SariAmbience.OnZoneEntered(other,zone));Assert.AreEqual(2,Heard());}
  [Test]public void NullArgumentsAreQuiet(){Assert.DoesNotThrow(()=>WorldAmbience.OnPlayerTurnEnded(null,zone));Assert.DoesNotThrow(()=>WorldAmbience.OnPlayerTurnEnded(player,null));Assert.False(SariAmbience.OnZoneEntered(null,zone));Assert.False(SariAmbience.OnZoneEntered(player,null));Assert.Zero(Heard());}
  [Test]public void ActualEmissionProducesExactlyOneActorDiagnostic(){MoveTo(AtTier(5));Assert.True(SariAmbience.OnZoneEntered(player,zone));Assert.False(SariAmbience.OnZoneEntered(player,zone));var records=DiagQuery.Apply(new DiagQuery.Filter{Kind="SariHeard",Actor=player.ID,Limit=10}).Records;Assert.AreEqual(1,records.Count);}
  public sealed class FactObserver:Part{public int Changes;public override bool HandleEvent(GameEvent e){if(e.ID=="IntPropertyChanged")Changes++;return true;}}
  public sealed class ForbiddenRandom:Random{public override int Next(int maxValue)=>throw new InvalidOperationException("gameplay RNG consumed");public override int Next(int minValue,int maxValue)=>throw new InvalidOperationException("gameplay RNG consumed");public override double NextDouble()=>throw new InvalidOperationException("gameplay RNG consumed");}
 }
}
