using System;
using System.Linq;
using CavesOfOoo.Core;
using NUnit.Framework;
namespace CavesOfOoo.Tests
{
 public sealed class DensityWorldRemarksTests
 {
  Entity player,speaker,chair;Zone zone;int ready;
  [SetUp]public void Setup(){FactionManager.Initialize();MessageLog.Clear();zone=new Zone("Overworld.2.2.0");player=Person("Player","you",10);player.SetTag("Player");speaker=Person("Scribe","Iven, scribe",12);chair=new Entity{BlueprintName="Chair"};chair.AddPart(new ChairPart{Occupied=true});zone.AddEntity(chair,12,10);speaker.AddPart(new StatusEffectsPart());Assert.True(speaker.ApplyEffect(new SittingEffect(chair)));ready=FindReady();MessageLog.Clear();player.IntProperties[WorldAmbience.HasMessageProperty]=0;player.IntProperties[WorldAmbience.TurnProperty]=ready;}
  [TearDown]public void Cleanup(){FactionManager.Reset();MessageLog.Clear();}
  Entity Person(string id,string name,int x){var e=new Entity{ID=id,BlueprintName=id};e.SetTag("Creature");e.Tags["Faction"]=id=="Player"?"Player":"Villagers";e.AddPart(new RenderPart{DisplayName=name});e.AddPart(new BrainPart());e.Statistics["Hitpoints"]=new Stat{Name="Hitpoints",BaseValue=20,Max=20};Assert.True(zone.AddEntity(e,x,10));zone.GetCell(x,10).IsVisible=true;return e;}
  int FindReady(){for(int i=0;i<2000;i++){player.IntProperties[WorldAmbience.TurnProperty]=i;if(WorldRemarks.TryEmit(player,zone))return i;}Assert.Fail("The actual seated scribe must have a passing cosmetic roll.");return 0;}
  [Test]public void AVisibleRestingSpeakerUsesItsActualNameAndContext(){Assert.True(WorldRemarks.TryEmit(player,zone));StringAssert.Contains("Iven, scribe",MessageLog.GetLast());StringAssert.Contains("hands",MessageLog.GetLast());Assert.AreEqual(ready,player.GetIntProperty(WorldAmbience.LastMessageProperty));}
  [TestCase("invisible")][TestCase("dead")][TestCase("death-handled")][TestCase("removed")][TestCase("hostile-speaker")][TestCase("hostile-listener")][TestCase("silent-frog")][TestCase("silent-remnant")][TestCase("no-chair")][TestCase("far-chair")][TestCase("busy")][TestCase("wall")][TestCase("far-speaker")]
  public void TheSamePassingRollCannotRevealInvalidOrSilentSpeakers(string condition){switch(condition){case "invisible":zone.GetCell(12,10).IsVisible=false;break;case "dead":speaker.GetStat("Hitpoints").BaseValue=0;break;case "death-handled":speaker.SetTag("_DeathHandled");break;case "removed":zone.RemoveEntity(speaker);break;case "hostile-speaker":speaker.GetPart<BrainPart>().PersonalEnemies.Add(player);break;case "hostile-listener":player.GetPart<BrainPart>().PersonalEnemies.Add(speaker);break;case "silent-frog":speaker.BlueprintName="GinFrog";break;case "silent-remnant":speaker.BlueprintName="GlassblownDrifter";break;case "no-chair":zone.RemoveEntity(chair);break;case "far-chair":zone.RemoveEntity(chair);zone.AddEntity(chair,30,10);break;case "busy":speaker.GetPart<BrainPart>().Target=player;break;case "wall":var wall=new Entity();wall.SetTag("Solid");zone.AddEntity(wall,11,10);break;case "far-speaker":zone.RemoveEntity(speaker);zone.AddEntity(speaker,30,10);zone.GetCell(30,10).IsVisible=true;break;}Assert.False(WorldRemarks.TryEmit(player,zone));Assert.AreEqual(0,MessageLog.GetMessages().Count);}
  [TestCase("dead")][TestCase("death-handled")][TestCase("removed")][TestCase("npc")]
  public void InvalidListenerCannotCauseRemarks(string condition){if(condition=="dead")player.GetStat("Hitpoints").BaseValue=0;if(condition=="death-handled")player.SetTag("_DeathHandled");if(condition=="removed")zone.RemoveEntity(player);if(condition=="npc")player.Tags.Remove("Player");Assert.False(WorldRemarks.TryEmit(player,zone));}
  [Test]public void SharedBudgetPreventsTwoRemarksOrSariAndRemark(){Assert.True(WorldRemarks.TryEmit(player,zone));Assert.False(WorldRemarks.TryEmit(player,zone));Assert.AreEqual(1,MessageLog.GetMessages().Count);player.IntProperties[WorldAmbience.TurnProperty]=ready+19;Assert.False(WorldRemarks.TryEmit(player,zone));}
  [Test]public void RestoredCosmeticBudgetDoesNotReplayTheLine(){Assert.True(WorldRemarks.TryEmit(player,zone));var loaded=PartRoundTripHelper.RoundTripEntity(player);zone.RemoveEntity(player);Assert.True(zone.AddEntity(loaded,10,10));Assert.False(WorldRemarks.TryEmit(loaded,zone));}
  [Test]public void SeveralSpeakersStillProduceOneLine(){var other=Person("Scribe","second scribe",13);other.AddPart(new StatusEffectsPart());Assert.True(other.ApplyEffect(new SittingEffect(chair)));Assert.True(WorldRemarks.TryEmit(player,zone));Assert.AreEqual(1,MessageLog.GetMessages().Count);}

  [TestCase("Innkeeper",true)][TestCase("Innkeeper",false)][TestCase("Farmer",true)][TestCase("Farmer",false)][TestCase("Warden",true)][TestCase("Warden",false)]
  public void OtherRolesNeedTheirExactConcreteContext(string role,bool context){speaker.BlueprintName=role;speaker.RemoveEffect<SittingEffect>();zone.RemoveEntity(chair);var old=TurnManager.Active;try{if(role=="Warden"){var turns=new TurnManager();turns.RestoreSavedState(context?900:0,false,null,new System.Collections.Generic.List<TurnManager.SavedTurnEntry>());}else if(context){var item=new Entity();if(role=="Innkeeper")item.AddPart(new CampfirePart());else item.AddPart(new WellSitePart());zone.AddEntity(item,12,11);}Assert.AreEqual(context,WorldRemarks.TryEmit(player,zone));}finally{typeof(TurnManager).GetProperty("Active").SetValue(null,old);}}
  [Test]public void ThrowingObserverCannotReplayACommittedRemark(){var old=MessageLog.OnMessage;try{MessageLog.OnMessage=_=>throw new InvalidOperationException("observer");Assert.DoesNotThrow(()=>Assert.True(WorldRemarks.TryEmit(player,zone)));Assert.False(WorldRemarks.TryEmit(player,zone));Assert.AreEqual(1,MessageLog.GetMessages().Count);}finally{MessageLog.OnMessage=old;}}
 }
}
