using System;
using System.Collections.Generic;
using System.Linq;
using CavesOfOoo.Core;
using NUnit.Framework;
namespace CavesOfOoo.Tests
{
 public sealed class DensityWorldTravellersAdversarialTests
 {
  DensityLootTestScope scope;OverworldZoneManager manager;Entity player;Zone zone;string readyId;
  [SetUp]public void Setup(){scope=new DensityLootTestScope();FactionManager.Initialize();manager=OverworldZoneManager.CreateDetached(scope.Factory,718);player=scope.Factory.CreateEntity("Player");readyId=FindWinningZone();ClearMemory();zone.RemoveEntity(zone.GetReadOnlyEntities().Single(e=>e.GetProperty(WorldTravellers.OriginProperty)!=null));}
  [TearDown]public void Cleanup(){scope.Dispose();FactionManager.Reset();}
  void ClearMemory(){foreach(var k in player.IntProperties.Keys.Where(k=>k.StartsWith("Traveller")).ToArray())player.IntProperties.Remove(k);foreach(var k in player.Properties.Keys.Where(k=>k.StartsWith("Traveller")).ToArray())player.Properties.Remove(k);}
  void Attach(Zone z){if(zone?.GetEntityCell(player)!=null)zone.RemoveEntity(player);zone=z;Assert.True(zone.AddEntity(player,10,10));manager.ReplaceLoadedState(new Dictionary<string,Zone>{{zone.ZoneID,zone}},zone.ZoneID,new Dictionary<string,List<ZoneConnection>>());}
  string FindWinningZone(){for(int x=0;x<WorldMap.Width;x++)for(int y=0;y<WorldMap.Height;y++){if(WorldMapAuthoring.TierAt(x,y)>3||manager.WorldMap.GetPOI(x,y)!=null)continue;Attach(new Zone(WorldMap.ToZoneID(x,y,0)));if(WorldTravellers.OnZoneEntered(player,zone))return zone.ZoneID;}Assert.Fail("At least one eligible zone must win the bounded entry roll.");return null;}
  Entity Spawn(){Assert.True(WorldTravellers.OnZoneEntered(player,zone));return zone.GetReadOnlyEntities().Single(e=>e.GetProperty(WorldTravellers.OriginProperty)!=null);}

  [TestCase("foreign-player")][TestCase("stale-identity")][TestCase("copied-route")][TestCase("same-endpoint-alias")]
  public void RouteClaimsRequireTheSavedEncounterAndDistinctCanonicalPlaces(string mode){var m=Spawn();Entity listener=player;if(mode=="foreign-player"){listener=scope.Factory.CreateEntity("Player");zone.AddEntity(listener,11,10);}if(mode=="stale-identity")m.ID="someone-else";if(mode=="copied-route"){var copy=scope.Factory.CreateEntity("Merchant");copy.Properties[WorldTravellers.OriginProperty]=m.GetProperty(WorldTravellers.OriginProperty);copy.Properties[WorldTravellers.DestinationProperty]=m.GetProperty(WorldTravellers.DestinationProperty);zone.AddEntity(copy,11,11);m=copy;}if(mode=="same-endpoint-alias"){var(x,y,z)=WorldMap.FromZoneID(m.GetProperty(WorldTravellers.OriginProperty));m.Properties[WorldTravellers.DestinationProperty]="Overworld."+x+"."+y;}Assert.AreEqual("fallback",WorldTravellers.DescribeConversation(m,listener,"Merchant_1","Start","fallback"));}
  [TestCase("negative-count")][TestCase("cap")][TestCase("already-zero-roll")]
  public void CorruptOrExhaustedMemoryFailsClosed(string mode){string seed=manager.WorldSeed.ToString(System.Globalization.CultureInfo.InvariantCulture);if(mode=="already-zero-roll")player.IntProperties["TravellerRoll:"+seed+":"+readyId]=0;else player.IntProperties["TravellerCount:"+seed]=mode=="cap"?3:-1;Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual(1,zone.GetReadOnlyEntities().Count);}
  [TestCase("interior")][TestCase("liquid")][TestCase("edge")]
  public void LegalPlacementPreservesUnsafeCellsAndFindsNoShortcut(string mode){for(int x=0;x<Zone.Width;x++)for(int y=0;y<Zone.Height;y++){if(mode=="interior")zone.GetCell(x,y).IsInterior=true;else if(mode=="liquid"){var e=new Entity();e.SetTag("Terrain");e.AddPart(new LiquidPoolPart());zone.AddEntity(e,x,y);}else if(x>1&&y>1&&x<Zone.Width-2&&y<Zone.Height-2)zone.GenReservedCells.Add((x,y));}int before=zone.GetReadOnlyEntities().Count;Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual(before,zone.GetReadOnlyEntities().Count);}
  [Test]public void DeterministicIdentityCollisionRefusesWithoutMutatingExistingActor(){string id="traveller:"+manager.WorldSeed+":"+readyId;var existing=new Entity{ID=id,BlueprintName="Unrelated"};zone.AddEntity(existing,20,20);Assert.False(WorldTravellers.OnZoneEntered(player,zone));Assert.AreEqual("Unrelated",existing.BlueprintName);Assert.AreEqual(2,zone.GetReadOnlyEntities().Count);}
  [Test]public void SpawnStartsItsNormalRestockClockAndUsesAnOpenUnreservedCell(){var m=Spawn();Assert.AreEqual(WorldClock.CurrentTick,m.GetIntProperty(TraderRestockSystem.LastRestockProp));var cell=zone.GetEntityCell(m);Assert.False(zone.GenReservedCells.Contains((cell.X,cell.Y)));Assert.GreaterOrEqual(cell.X,2);Assert.Less(cell.X,Zone.Width-2);Assert.AreEqual(1,cell.Objects.Count);Assert.AreSame(zone,m.GetPart<BrainPart>().CurrentZone);}
  [Test]public void FullWorldGraphPreservesConsumedStockPurseActorRouteAndEntryMemory(){var m=Spawn();string id=m.ID;var inv=m.GetPart<InventoryPart>();foreach(var item in inv.Objects.ToArray())inv.RemoveObject(item);TradeSystem.SetDrams(m,17);var oldTurns=TurnManager.Active;try{var turns=new TurnManager();turns.RestoreSavedState(71,true,player,new List<TurnManager.SavedTurnEntry>{new TurnManager.SavedTurnEntry{Entity=player,Energy=1000},new TurnManager.SavedTurnEntry{Entity=m,Energy=0}});var state=GameSessionState.Capture("traveller-test","v",manager,turns,player);GameSessionState loaded;using(var stream=new System.IO.MemoryStream()){state.Save(new SaveWriter(stream));stream.Position=0;loaded=GameSessionState.Load(new SaveReader(stream,scope.Factory));}var saved=loaded.ZoneManager.ActiveZone.GetReadOnlyEntities().Single(e=>e.ID==id);Assert.AreEqual(0,saved.GetPart<InventoryPart>().Objects.Count);Assert.AreEqual(17,TradeSystem.GetDrams(saved));Assert.AreNotEqual("fallback",WorldTravellers.DescribeConversation(saved,loaded.Player,"Merchant_1","Sources","fallback"));Assert.False(WorldTravellers.OnZoneEntered(loaded.Player,loaded.ZoneManager.ActiveZone));Assert.AreEqual(2,loaded.ZoneManager.ActiveZone.GetReadOnlyEntities().Count);}finally{typeof(TurnManager).GetProperty("Active").SetValue(null,oldTurns);}}
  [TestCase("player-dead")][TestCase("player-handled")][TestCase("speaker-hp-zero")][TestCase("speaker-hostile")][TestCase("listener-hostile")]
  public void RouteDecoratorRejectsDeadOrHostileParticipants(string mode){var m=Spawn();if(mode=="player-dead")player.GetStat("Hitpoints").BaseValue=0;if(mode=="player-handled")player.SetTag("_DeathHandled");if(mode=="speaker-hp-zero")m.GetStat("Hitpoints").BaseValue=0;if(mode=="speaker-hostile")m.GetPart<BrainPart>().PersonalEnemies.Add(player);if(mode=="listener-hostile")player.GetPart<BrainPart>().PersonalEnemies.Add(m);Assert.AreEqual("fallback",WorldTravellers.DescribeConversation(m,player,"Merchant_1","Start","fallback"));}
 }
}
