using System;using System.Collections.Generic;using System.Linq;using System.IO;using NUnit.Framework;using CavesOfOoo.Core;using CavesOfOoo.Data;using CavesOfOoo.Diagnostics;
namespace CavesOfOoo.Tests
{
 public sealed class DensityUndergroundRoutesAdversarialTests
 {
  DensityLootTestScope scope;Zone zone;Entity up,down;
  [SetUp]public void Setup(){scope=new DensityLootTestScope();zone=new Zone("Overworld.9.11.3");up=scope.Factory.CreateEntity("StairsUp");down=scope.Factory.CreateEntity("StairsDown");zone.AddEntity(up,30,12);zone.AddEntity(down,45,12);}
  [TearDown]public void Cleanup(){scope.Dispose();}
  bool Build()=>new UndergroundRouteReservationBuilder().BuildZone(zone,scope.Factory,new DensitySariAdversarialTests.ForbiddenRandom());
  void Wall(int x,int y){var e=new Entity();e.SetTag("Solid");zone.AddEntity(e,x,y);}
  [Test]public void ExistingFourExitAndStairPathsAreReservedWithoutCarvingOrReplacingOwners(){var old=zone.GetReadOnlyEntities().ToArray();Assert.True(Build());CollectionAssert.AreEquivalent(old,zone.GetReadOnlyEntities());Assert.True(zone.GenReservedCells.Any(c=>c.x==0));Assert.True(zone.GenReservedCells.Any(c=>c.x==79));Assert.True(zone.GenReservedCells.Any(c=>c.y==0));Assert.True(zone.GenReservedCells.Any(c=>c.y==24));foreach(var e in old){var c=zone.GetEntityCell(e);Assert.True(zone.GenReservedCells.Contains((c.X,c.Y)));}}
  [TestCase("west")][TestCase("east")][TestCase("north")][TestCase("south")]
  public void MissingRealEdgeRouteFailsWithoutPublishingPartialReservations(string edge){for(int x=0;x<80;x++)for(int y=0;y<25;y++)if(edge=="west"&&x==0||edge=="east"&&x==79||edge=="north"&&y==0||edge=="south"&&y==24)Wall(x,y);Assert.False(Build());Assert.Zero(zone.GenReservedCells.Count);}
  [Test]public void NoStairsCannotInventAnArrival(){zone.RemoveEntity(up);zone.RemoveEntity(down);Assert.False(Build());Assert.Zero(zone.GenReservedCells.Count);Assert.Zero(zone.EntityCount);}
  [Test]public void ABlockedStairCannotBeCertifiedOrSilentlyCleared(){Wall(45,12);int count=zone.EntityCount;Assert.False(Build());Assert.AreEqual(count,zone.EntityCount);Assert.Zero(zone.GenReservedCells.Count);}
  [Test]public void DisconnectedStairsRefuseWithoutMakingATunnel(){for(int y=0;y<25;y++)Wall(40,y);Assert.False(Build());Assert.True(zone.GetCell(40,12).BlocksMovement());Assert.Zero(zone.GenReservedCells.Count);}
  [TestCase(false)][TestCase(true)]public void ExistingReservationsSurviveSuccessAndRefusal(bool fail){zone.GenReservedCells.Add((70,20));if(fail){zone.RemoveEntity(up);zone.RemoveEntity(down);}Assert.AreEqual(!fail,Build());Assert.True(zone.GenReservedCells.Contains((70,20)));}
  [Test]public void MissingZoneRefuses(){Assert.False(new UndergroundRouteReservationBuilder().BuildZone(null,scope.Factory,new Random(1)));}
  [Test]public void RouteSelectionDoesNotReadRandomOrConsumeGameplayFacts(){var observe=new DensitySariAdversarialTests.FactObserver();up.AddPart(observe);Assert.True(Build());Assert.Zero(observe.Changes);}
  [TestCase("0,0;1,0")][TestCase("2,0;3,0")]
  public void EveryOccupiedStairBodyCellAndItsClearApproachAreReserved(string footprint){zone.RemoveEntity(up);up.AddPart(new SpatialFootprintPart{CellsRaw=footprint});Assert.True(zone.AddEntity(up,30,12));Assert.True(Build());foreach(var c in zone.GetOccupiedCells(up)){Assert.True(zone.GenReservedCells.Contains((c.X,c.Y)));Assert.True(zone.GenReservedCells.Contains((c.X,c.Y+1)));}}
  [TestCase(true)][TestCase(false)]public void OneSurvivingStairStillGetsRealHorizontalReturnPaths(bool keepUp){zone.RemoveEntity(keepUp?down:up);Assert.True(Build());Assert.True(zone.GenReservedCells.Any(c=>c.x==0));Assert.True(zone.GenReservedCells.Any(c=>c.x==79));}
  [Test]public void RemovedStairDoesNotGetRecreatedByReservation(){Assert.True(Build());zone.RemoveEntity(up);zone.RemoveEntity(down);Assert.False(Build());Assert.Zero(zone.EntityCount);}
  [Test]public void OrdinaryPopulationStillSpawnsOffTheProtectedRoute(){Assert.True(Build());var table=new PopulationTable{Name="route countercheck",Entries=new List<PopulationEntry>{new PopulationEntry{BlueprintName="MarlbackScrabbler",MinCount=3,MaxCount=3,Weight=1}}};Assert.True(new PopulationBuilder(table).BuildZone(zone,scope.Factory,new Random(1)));var actors=zone.GetEntitiesWithTag("Creature");Assert.AreEqual(3,actors.Count);foreach(var e in actors)foreach(var c in zone.GetOccupiedCells(e))Assert.False(zone.GenReservedCells.Contains((c.X,c.Y)));}
  [TestCase(false)][TestCase(true)]public void DiagnosticHonorsWorldgenChannel(bool enabled){bool before=Diag.IsChannelEnabled("worldgen");string id="Overworld.route-diag-"+Guid.NewGuid().ToString("N");zone.ZoneID=id;try{Diag.SetChannel("worldgen",enabled);using(Diag.WithCause(id)){Assert.True(Build());}var records=DiagQuery.Apply(new DiagQuery.Filter{Kind="UndergroundRoutesReserved",CauseTraceId=id,Limit=100}).Records;Assert.AreEqual(enabled?1:0,records.Count(r=>r.PayloadJson!=null&&r.PayloadJson.Contains(id)));}finally{Diag.SetChannel("worldgen",before);}}
  string RoomId(OverworldZoneManager m,int depth){for(int x=0;x<20;x++)for(int y=0;y<20;y++){string id=WorldMap.ToZoneID(x,y,depth);if(UndergroundLayoutPlan.Select(m.WorldSeed,id,m.WorldMap.GetBiome(x,y),m.WorldMap.GetPOI(x,y),scope.Factory).IsRoomed)return id;}throw new Exception("roomed control");}
  [Test]public void SavedCachedRoomDoesNotRegenerateDestroyedStairsOrLoot(){var m=OverworldZoneManager.CreateDetached(scope.Factory,64);var z=m.GetZone(RoomId(m,7));m.SetActiveZone(z);foreach(var e in z.GetReadOnlyEntities().Where(e=>e.HasPart<StairsUpPart>()||e.HasPart<StairsDownPart>()).ToArray())z.RemoveEntity(e);var container=z.GetReadOnlyEntities().FirstOrDefault(e=>e.HasPart<ContainerPart>());if(container!=null)container.GetPart<ContainerPart>().Contents.Clear();var player=scope.Factory.CreateEntity("Player");var c=z.GetReadOnlyEntities().Select(e=>z.GetEntityCell(e)).First(cell=>!cell.BlocksMovement());z.AddEntity(player,c.X,c.Y);int count=z.EntityCount;var oldTurns=TurnManager.Active;try{var turns=new TurnManager();turns.RestoreSavedState(0,true,player,new List<TurnManager.SavedTurnEntry>{new TurnManager.SavedTurnEntry{Entity=player,Energy=1000}});var state=GameSessionState.Capture("underground-layout","test",m,turns,player);using(var stream=new MemoryStream()){state.Save(new SaveWriter(stream));stream.Position=0;var loaded=GameSessionState.Load(new SaveReader(stream,scope.Factory));var saved=loaded.ZoneManager.ActiveZone;Assert.AreSame(saved,loaded.ZoneManager.GetZone(saved.ZoneID));Assert.AreEqual(count,saved.EntityCount);Assert.False(saved.GetReadOnlyEntities().Any(e=>e.HasPart<StairsUpPart>()||e.HasPart<StairsDownPart>()));if(container!=null)Assert.Zero(saved.GetReadOnlyEntities().Single(e=>e.ID==container.ID).GetPart<ContainerPart>().Contents.Count);}}finally{typeof(TurnManager).GetProperty("Active").SetValue(null,oldTurns);}}
  [Test]public void LowerFirstRoomedFloorKeepsTheExistingReciprocalGraph(){var m=OverworldZoneManager.CreateDetached(scope.Factory,64);string id=RoomId(m,7);var lower=m.GetZone(id);var up=lower.GetReadOnlyEntities().Single(e=>e.HasPart<StairsUpPart>());var before=lower.GetEntityCell(up);var parent=m.GetZone(WorldMap.GetZoneAbove(id));Assert.NotNull(parent);var edge=m.GetConnectionsTo(id,"StairsDown").Single();Assert.AreEqual(before.X,edge.TargetX);Assert.AreEqual(before.Y,edge.TargetY);Assert.True(parent.GetCell(edge.SourceX,edge.SourceY).Occupants.Any(e=>e.HasPart<StairsDownPart>()));Assert.AreSame(lower,m.GetZone(id));Assert.AreSame(up,lower.GetReadOnlyEntities().Single(e=>e.HasPart<StairsUpPart>()));}
 }
}
