using CavesOfOoo.Rendering;using NUnit.Framework;using UnityEngine;
namespace CavesOfOoo.Tests{public sealed class SpreadParticleSignalRenderingTests{
 [TestCase('!',true)][TestCase('z',true)][TestCase('V',true)][TestCase('*',false)][TestCase('Z',false)]
 public void ActualMeaningfulSignalHasDistinctSubmittedGeometryWhileDecorationsShareTheSpark(char glyph,bool distinct)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0"))using(var frame=new SpreadParticleFrame(((SpawnRing3DPresenter)f.Presenter).ActiveSurface,f.Library.WorldMaterial)){frame.BeginFrame(f.Zone);Assert.True(frame.TryDraw(20,10,'*',"&Y"));frame.EndFrame();Assert.True(frame.TryGet(20,10,out var root));var spark=root.GetComponent<MeshFilter>().sharedMesh;var vertices=spark.vertices;frame.BeginFrame(f.Zone);Assert.True(frame.TryDraw(20,10,glyph,"&Y"));frame.EndFrame();Assert.True(frame.TryGet(20,10,out root));var current=root.GetComponent<MeshFilter>().sharedMesh;Assert.AreEqual(distinct,!ReferenceEquals(current,spark));Assert.Greater(current.vertexCount,0);Assert.Greater(current.triangles.Length,0);if(distinct)CollectionAssert.AreNotEqual(vertices,current.vertices);else CollectionAssert.AreEqual(vertices,current.vertices);Assert.LessOrEqual(current.bounds.size.x,1);Assert.LessOrEqual(current.bounds.size.z,1);}}
 [Test] public void SleepDiagonalConnectsTopRightToBottomLeftInWorldPlane()
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0"))using(var frame=new SpreadParticleFrame(((SpawnRing3DPresenter)f.Presenter).ActiveSurface,f.Library.WorldMaterial)){frame.BeginFrame(f.Zone);Assert.True(frame.TryDraw(20,10,'z',"&Y"));frame.EndFrame();Assert.True(frame.TryGet(20,10,out var root));var vertices=root.GetComponent<MeshFilter>().sharedMesh.vertices;Assert.AreEqual(72,vertices.Length);float quadrant=0;for(int i=24;i<48;i++)quadrant+=vertices[i].x*vertices[i].z;Assert.Greater(quadrant,0,"The diagonal must join the top-right and bottom-left bars, not mirror the sleep Z.");}}
 [Test]public void NumericUiNeverBecomesALetterOrAlertVolume()
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0"))using(var frame=new SpreadParticleFrame(((SpawnRing3DPresenter)f.Presenter).ActiveSurface,f.Library.WorldMaterial)){frame.BeginFrame(f.Zone);Assert.True(frame.TryDraw(20,10,'!',"&Y"));Assert.False(frame.TryDraw(20,10,'7',"&Y"));frame.EndFrame();Assert.False(frame.TryGet(20,10,out _));}}
}}
