using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using CavesOfOoo.Core;
using CavesOfOoo.Core.Anatomy;
using CavesOfOoo.Rendering;
using NUnit.Framework;
using UnityEngine;
namespace CavesOfOoo.Tests {
public sealed class SpreadPortableDynamicTests {
private DensityLootTestScope scope; private Dictionary<string,LiquidDefinition> old;private bool initialized;
private static FieldInfo Registry=>typeof(LiquidRegistry).GetField("_byId",BindingFlags.Static|BindingFlags.NonPublic);
private static FieldInfo State=>typeof(LiquidRegistry).GetField("_initialized",BindingFlags.Static|BindingFlags.NonPublic);
[SetUp]public void Setup(){scope=new DensityLootTestScope();old=new Dictionary<string,LiquidDefinition>((Dictionary<string,LiquidDefinition>)Registry.GetValue(null));initialized=LiquidRegistry.IsInitialized;LiquidRegistry.InitializeFromJsonSources(Directory.GetFiles(Path.Combine(Application.dataPath,"Resources/Content/Data/LiquidDefinitions"),"*.json").OrderBy(x=>x).Select(File.ReadAllText));}
[TearDown]public void Cleanup(){var live=(Dictionary<string,LiquidDefinition>)Registry.GetValue(null);live.Clear();foreach(var pair in old)live.Add(pair.Key,pair.Value);State.SetValue(null,initialized);scope.Dispose();}
[TestCase("MarlbackScrabbler","MarlbackCorpse","marlback")]
[TestCase("Player","CreatureCorpse","humanoid")]
[TestCase("MarlbackGleaner","MarlbackCorpse","marlback")]
[TestCase("MarlbackTunnelguard","MarlbackCorpse","marlback")]
[TestCase("Elder","CreatureCorpse","humanoid")]
[TestCase("Villager","CreatureCorpse","humanoid")]
[TestCase("Weaponsmith","CreatureCorpse","humanoid")]
[TestCase("Armorer","CreatureCorpse","humanoid")]
[TestCase("Apothecary","CreatureCorpse","humanoid")]
[TestCase("Arcanist","CreatureCorpse","humanoid")]
[TestCase("Provisioner","CreatureCorpse","humanoid")]
[TestCase("CaveHermit","CreatureCorpse","humanoid")]
[TestCase("DesertHermit","CreatureCorpse","humanoid")]
[TestCase("JungleHermit","CreatureCorpse","humanoid")]
[TestCase("RuinsHermit","CreatureCorpse","humanoid")]
[TestCase("Marceline","CreatureCorpse","humanoid")]
[TestCase("Magpie","CreatureCorpse","avian")]
[TestCase("PetDog","CreatureCorpse","quadruped")]
[TestCase("VillageChild","CreatureCorpse","humanoid")]
[TestCase("Tinker","CreatureCorpse","humanoid")]
[TestCase("Merchant","CreatureCorpse","humanoid")]
[TestCase("Quartermaster","CreatureCorpse","humanoid")]
[TestCase("ChoirTendril","CreatureCorpse","plant")]
[TestCase("PalimpsestEcho","CreatureCorpse","humanoid")]
[TestCase("SaccharineEnvoy","CreatureCorpse","humanoid")]
[TestCase("ConcordFactor","CreatureCorpse","humanoid")]
[TestCase("PaleCurator","CreatureCorpse","humanoid")]
[TestCase("GlassblownDrifter","CreatureCorpse","humanoid")]
[TestCase("CaveBat","CreatureCorpse","bat")]
[TestCase("CaveSlime","CreatureCorpse","slime")]
[TestCase("CaveBear","CreatureCorpse","quadruped")]
[TestCase("Glowmaw","CreatureCorpse","ambush-maw")]
[TestCase("Scorpion","CreatureCorpse","scorpion")]
[TestCase("DesertBandit","CreatureCorpse","humanoid")]
[TestCase("SandWurm","CreatureCorpse","serpent")]
[TestCase("GiantSpider","CreatureCorpse","spider")]
[TestCase("Viper","CreatureCorpse","serpent")]
[TestCase("JungleApe","CreatureCorpse","ape")]
[TestCase("RuinScavenger","CreatureCorpse","humanoid")]
[TestCase("SkeletalSentry","CreatureCorpse","skeleton")]
[TestCase("StoneGolem","CreatureCorpse","construct")]
[TestCase("PaleStalker","CreatureCorpse","stalker")]
[TestCase("ObsidianBrute","CreatureCorpse","construct")]
[TestCase("MarlbackWallkeeper","MarlbackCorpse","marlback")]
[TestCase("MarlbackBreacher","MarlbackCorpse","marlback")]
[TestCase("Mosshulk","CreatureCorpse","fungal")]
[TestCase("DesertProwler","CreatureCorpse","quadruped")]
[TestCase("DuneLurker","CreatureCorpse","ambush-maw")]
[TestCase("BrittleHound","CreatureCorpse","quadruped")]
[TestCase("JungleStalker","CreatureCorpse","quadruped")]
[TestCase("Rotling","CreatureCorpse","fungal")]
[TestCase("CanopyStrangler","CreatureCorpse","plant")]
[TestCase("AncientGuardian","CreatureCorpse","construct")]
[TestCase("VaultSentinel","CreatureCorpse","construct")]
[TestCase("BrassHusk","CreatureCorpse","construct")]
[TestCase("GlassScorpion","CreatureCorpse","scorpion")]
[TestCase("SporeShambler","CreatureCorpse","fungal")]
[TestCase("Mogu","CreatureCorpse","humanoid")]
[TestCase("Grib","CreatureCorpse","humanoid")]
[TestCase("Nam","CreatureCorpse","humanoid")]
[TestCase("Sien","CreatureCorpse","humanoid")]
[TestCase("Sopp","CreatureCorpse","humanoid")]
[TestCase("IceWight","CreatureCorpse","skeleton")]
[TestCase("CharredHusk","CreatureCorpse","charred-humanoid")]
[TestCase("Warden","CreatureCorpse","humanoid")]
[TestCase("WellKeeper","CreatureCorpse","humanoid")]
[TestCase("Farmer","CreatureCorpse","humanoid")]
[TestCase("Innkeeper","CreatureCorpse","humanoid")]
[TestCase("Undertaker","CreatureCorpse","humanoid")]
[TestCase("Scribe","CreatureCorpse","humanoid")]
[TestCase("SleepingTroll","CreatureCorpse","troll")]
[TestCase("MimicChest","CreatureCorpse","mimic")]
[TestCase("AmbushBandit","CreatureCorpse","humanoid")]
[TestCase("RuneCultist","CreatureCorpse","humanoid")]
[TestCase("SunStriker","CreatureCorpse","lizard")]
[TestCase("TentRightHost","CreatureCorpse","humanoid")]
[TestCase("SaltMaster","CreatureCorpse","humanoid")]
[TestCase("Reedfrog","CreatureCorpse","frog")]
[TestCase("Bandfrog","CreatureCorpse","frog")]
[TestCase("MawToad","CreatureCorpse","frog")]
[TestCase("GinFrog","CreatureCorpse","frog")]
[TestCase("RecensionScribe","CreatureCorpse","humanoid")]
[TestCase("StillleafSearcher","CreatureCorpse","humanoid")]
[TestCase("CurationSorter","CreatureCorpse","humanoid")]
[TestCase("StillleafIndexer","CreatureCorpse","humanoid")]
[TestCase("PeatCutter","CreatureCorpse","humanoid")]
[TestCase("FilerClerk","CreatureCorpse","humanoid")]
[TestCase("EncasedElder","CreatureCorpse","humanoid")]
[TestCase("CatacombWarden","CreatureCorpse","humanoid")]
[TestCase("PlaqueTender","CreatureCorpse","humanoid")]
[TestCase("SariSnake","CreatureCorpse","serpent")]
[TestCase("Wardline","CreatureCorpse","serpent")]
[TestCase("CascadeFather","CreatureCorpse","frog")]
[TestCase("GlasspaneFrog","CreatureCorpse","frog")]
[TestCase("YellowfootWayfarer","CreatureCorpse","tortoise")]
[TestCase("Shambler","CreatureCorpse","fungal")]
[TestCase("GroveLanternMoth","CreatureCorpse","moth")]
[TestCase("SummitSinger","CreatureCorpse","frog")]
[TestCase("BrocchiniaSentinel","CreatureCorpse","lizard")]
[TestCase("SkySari","CreatureCorpse","avian")]
[TestCase("PrickleBrowGecko","CreatureCorpse","lizard")]
[TestCase("HelmwoodFrog","CreatureCorpse","frog")]
[TestCase("FoundingListener","CreatureCorpse","humanoid")]
[TestCase("FoundingPlaqueTender","CreatureCorpse","humanoid")]
[TestCase("GantryRegistrar","CreatureCorpse","humanoid")]
[TestCase("SootGremlin","CreatureCorpse","humanoid")]
[TestCase("DirtGnome","CreatureCorpse","humanoid")]
public void ActualCorpseRetainsSourceAnatomy(string source,string blueprint,string family){var item=scope.Factory.CreateEntity(blueprint);item.Properties["SourceBlueprint"]=source;item.Properties["SourceID"]="deceased-owner";Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id));Assert.AreEqual(family=="marlback"?"spread-portable-marlbackcorpse":"spread-portable-corpse-"+family,id);Assert.AreEqual(source,item.Properties["SourceBlueprint"]);}
[TestCase("UnknownSpecies")][TestCase("Dagger")][TestCase("")][TestCase("MarlbackScrabbler")]
public void GenericCorpseCannotBorrowUnknownOrWrongNativeCorpseRecipe(string source){var item=scope.Factory.CreateEntity("CreatureCorpse");item.Properties["SourceBlueprint"]=source;item.Properties["SourceID"]="old";Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[Test]public void MarlbackCorpseRefusesOtherSpecies(){var item=scope.Factory.CreateEntity("MarlbackCorpse");item.Properties["SourceBlueprint"]="CaveBear";item.Properties["SourceID"]="old";Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[TestCase("Head")][TestCase("Arm")][TestCase("Hand")][TestCase("Feet")][TestCase("Tail")][TestCase("Body")][TestCase("Wing")][TestCase("Tendril")]
public void RealSeveredFactoryUsesKnownCategoryAndLiteralPartShape(string type){for(int category=1;category<=21;category++){var item=SeveredLimbFactory.Create(new BodyPart{Type=type,Name=type,Category=category});Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id),category+":"+type);Assert.AreEqual("spread-portable-limb-"+category+"-"+type.ToLowerInvariant(),id);}}
[TestCase(-1,"Arm")][TestCase(22,"Arm")][TestCase(1,"UnknownPart")][TestCase(1,"")]
public void MalformedSeveredMetadataRefuses(int category,string type){var item=SeveredLimbFactory.Create(new BodyPart{Type=type,Name="part",Category=category});Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[TestCase("DetectiveNotebook")][TestCase("CrunchyLocket")]
public void ActualConstructedPortableIdentityHasAuthoredForm(string name){var item=new Entity{BlueprintName=name};item.SetTag("Item");item.AddPart(new RenderPart());item.AddPart(new PhysicsPart{Takeable=true});Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id));Assert.AreEqual("spread-portable-"+name.ToLowerInvariant(),id);}
[TestCase("Coating")][TestCase("Throwable")][TestCase("Food")]
public void BrewFormUsesCurrentProductionField(string form){var item=scope.Factory.CreateEntity("BrewedTonic");item.AddPart(new BrewItemPart{Form=form});Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id));Assert.AreEqual("spread-portable-brew-"+form.ToLowerInvariant(),id);}
[TestCase("Unknown")][TestCase("")][TestCase(null)]public void UnknownBrewFormRefuses(string form){var item=scope.Factory.CreateEntity("BrewedTonic");item.AddPart(new BrewItemPart{Form=form});Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[TestCase("SteelBladeComponent","OakHaftComponent","LeatherBindingComponent")]
[TestCase("SteelBladeComponent","OakHaftComponent","SerratedEdgeComponent")]
[TestCase("SteelBladeComponent","WillowHaftComponent","LeatherBindingComponent")]
[TestCase("SteelBladeComponent","WillowHaftComponent","SerratedEdgeComponent")]
[TestCase("IronSpikeComponent","OakHaftComponent","LeatherBindingComponent")]
[TestCase("IronSpikeComponent","OakHaftComponent","SerratedEdgeComponent")]
[TestCase("IronSpikeComponent","WillowHaftComponent","LeatherBindingComponent")]
[TestCase("IronSpikeComponent","WillowHaftComponent","SerratedEdgeComponent")]
public void RealAssemblyFieldsSelectBladeHaftBinding(string blade,string haft,string binding){var item=scope.Factory.CreateEntity("ForgedWeapon");item.AddPart(new WeaponAssemblyPart{BladeBlueprint=blade,HaftBlueprint=haft,BindingBlueprint=binding});Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id));Assert.AreEqual("spread-portable-forged-"+(blade=="SteelBladeComponent"?"blade":"spike")+"-"+(haft=="OakHaftComponent"?"oak":"willow")+"-"+(binding=="LeatherBindingComponent"?"leather":"serrated"),id);}
[Test]public void UnknownAssemblyCannotClaimKnownBlade(){var item=scope.Factory.CreateEntity("ForgedWeapon");item.AddPart(new WeaponAssemblyPart{BladeBlueprint="Unknown",HaftBlueprint="OakHaftComponent",BindingBlueprint="LeatherBindingComponent"});Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[TestCase("veined-pulse-mycelium","&m")]
[TestCase("felling-counter-resin","&y")]
[TestCase("choir-wort","&g")]
[TestCase("gel","&c")]
[TestCase("lantern-beetle-ichor","&Y")]
[TestCase("bower-resin-amber","&Y")]
[TestCase("brine","&c")]
[TestCase("carapace-ichor","&g")]
[TestCase("lumen-slime","&C")]
[TestCase("tepuibone-slurry","&W")]
[TestCase("convalessence","&B")]
[TestCase("water","&c")]
[TestCase("memory-bath","&B")]
[TestCase("honey","&Y")]
[TestCase("ice","&C")]
[TestCase("oil","&K")]
[TestCase("held-breath-lacquer","&W")]
[TestCase("lava","&R")]
[TestCase("iron-gall-ink","&K")]
[TestCase("sap","&w")]
[TestCase("sundew-mucilage","&G")]
[TestCase("acid","&G")]
[TestCase("bog-mire","&y")]
[TestCase("pebble-sundew-dew","&G")]
[TestCase("pitch","&K")]
[TestCase("choir-mirror-mucilage","&C")]
public void FilledFlaskShowsRegisteredCurrentColor(string liquid,string color){var item=scope.Factory.CreateEntity("LiquidFlask");var flask=item.GetPart<LiquidVesselPart>();flask.Volume=6;flask.LiquidId=liquid;Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id));Assert.AreEqual("spread-portable-flask-"+((int)color[1]).ToString("x2"),id);flask.Volume=0;flask.LiquidId="";Assert.True(SpreadPortableRecipes.TryRecipe(item,out id));Assert.AreEqual("spread-portable-liquidflask",id);}
}}
