using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;using System.Reflection;
using CavesOfOoo.Core;using CavesOfOoo.Rendering;using NUnit.Framework;using UnityEngine;
namespace CavesOfOoo.Tests{public sealed class SpreadSurfaceMarkRenderingTests{
 Dictionary<string,LiquidDefinition> prior;bool oldInit;IList reactions;object[] oldReactions;bool oldReactionInit;
 static FieldInfo Map=>typeof(LiquidRegistry).GetField("_byId",BindingFlags.NonPublic|BindingFlags.Static);static FieldInfo Init=>typeof(LiquidRegistry).GetField("_initialized",BindingFlags.NonPublic|BindingFlags.Static);
 [SetUp]public void Setup(){prior=new Dictionary<string,LiquidDefinition>((Dictionary<string,LiquidDefinition>)Map.GetValue(null));oldInit=LiquidRegistry.IsInitialized;LiquidRegistry.InitializeFromJsonSources(Directory.GetFiles(Path.Combine(Application.dataPath,"Resources/Content/Data/LiquidDefinitions"),"*.json").Select(File.ReadAllText));reactions=(IList)typeof(TileReactionSystem).GetField("_reactions",BindingFlags.NonPublic|BindingFlags.Static).GetValue(null);oldReactions=reactions.Cast<object>().ToArray();oldReactionInit=TileReactionSystem.IsInitialized;TileReactionSystem.Initialize(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Data/TileReactions/Reactions.json")));}
 [TearDown]public void Clean(){var map=(Dictionary<string,LiquidDefinition>)Map.GetValue(null);map.Clear();foreach(var p in prior)map.Add(p.Key,p.Value);Init.SetValue(null,oldInit);reactions.Clear();foreach(var r in oldReactions)reactions.Add(r);typeof(TileReactionSystem).GetField("<IsInitialized>k__BackingField",BindingFlags.NonPublic|BindingFlags.Static).SetValue(null,oldReactionInit);}
 static bool View(SpawnRing3DIntegrationFixture f,out GameObject root,out SpreadTransientSample sample)=>((SpawnRing3DPresenter)f.Presenter).TryGetElementVolume(20,10,out root,out sample);
 static void Near(Color a,Color b){Assert.That(a.r,Is.EqualTo(b.r).Within(.000001f));Assert.That(a.g,Is.EqualTo(b.g).Within(.000001f));Assert.That(a.b,Is.EqualTo(b.b).Within(.000001f));Assert.That(a.a,Is.EqualTo(b.a).Within(.000001f));}
 [TestCase("water",.3f,.55f,.95f)][TestCase("oil",.35f,.25f,.45f)][TestCase("ice",.85f,.95f,1f)][TestCase("acid",.3f,.55f,.95f)]
 [TestCase("embers",1f,.45f,.1f)][TestCase("petals",.6f,.6f,.6f)]
 public void ActualPrioritizedSurfaceMarkKeepsOriginalTintAndLowGroundGeometry(string id,float r,float g,float b)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0")){f.Zone.TileState.Clear(20,10);bool residue=id=="embers"||id=="petals";if(residue)f.Zone.TileState.WriteResidue(20,10,id,3);else f.Zone.TileState.WriteCoating(20,10,id,3);string state=f.Zone.TileState.ToSaveString();f.Refresh();Assert.True(View(f,out var root,out var s));Assert.AreEqual((residue?"residue:":"coating:")+id,s.Kind);Assert.AreEqual(3,s.Amount);var mesh=root.GetComponent<MeshFilter>().sharedMesh;Assert.NotNull(mesh);Assert.Greater(mesh.vertexCount,0);Assert.LessOrEqual(mesh.bounds.max.y,.15f);var block=new MaterialPropertyBlock();root.GetComponent<MeshRenderer>().GetPropertyBlock(block);Near(new Color(r,g,b).linear,block.GetColor("_BaseColor"));Assert.AreEqual(state,f.Zone.TileState.ToSaveString());}}
 [TestCase(false)][TestCase(true)]public void RealTileReactionChoosesActualSmokeResidueOrSteamSource(bool oil)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0")){f.Zone.TileState.Clear(20,10);f.Zone.TileState.WriteCoating(20,10,oil?"oil":"water",3);f.Zone.TileState.AddHeat(20,10,1);Assert.GreaterOrEqual(TileReactionSystem.ResolveZone(f.Zone),1);string state=f.Zone.TileState.ToSaveString();f.Refresh();Assert.True(View(f,out _,out var s));Assert.AreEqual(oil?"residue:embers":"steam",s.Kind);Assert.AreEqual(oil?"smoke":"steam",f.Zone.TileState.Cloud(20,10));Assert.AreEqual(state,f.Zone.TileState.ToSaveString());}}
 [TestCase("unknown-residue")][TestCase("unknown-coating")][TestCase("hidden")][TestCase("removed")]
 public void UnsupportedOrRetiredSurfaceDoesNotReuseTheOldMark(string fault)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0")){f.Zone.TileState.Clear(20,10);f.Zone.TileState.WriteResidue(20,10,"petals",2);f.Refresh();Assert.True(View(f,out var old,out _));if(fault=="hidden")f.Zone.GetCell(20,10).IsVisible=false;else{f.Zone.TileState.Clear(20,10);if(fault=="unknown-residue")f.Zone.TileState.WriteResidue(20,10,"alien",3);else if(fault=="unknown-coating")f.Zone.TileState.WriteCoating(20,10,"alien",3);}f.Refresh();Assert.False(View(f,out _,out _));SpawnRing3DIntegrationFixture.Hidden(old);}}
 [TestCase("foreign")][TestCase("unexplored")][TestCase("unknown-priority")]
 public void CurrentAuthorityOrUnknownHigherPriorityRefusesAnExistingValidGroundMark(string change)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0")){f.Zone.TileState.Clear(20,10);f.Zone.TileState.WriteCoating(20,10,"water",3);f.Zone.TileState.AddCharge(20,10,2);f.Refresh();Assert.True(View(f,out var old,out _));if(change=="foreign")f.Manager.WorldMap.Tiles[12,10]=BiomeType.Sodden;else if(change=="unexplored")f.Zone.GetCell(20,10).Explored=false;else f.Zone.TileState.WriteResidue(20,10,"unregistered-first",2);Assert.False(View(f,out _,out _),"A stale ground mark cannot suppress the current source before Refresh.");f.Refresh();Assert.False(View(f,out _,out _));SpawnRing3DIntegrationFixture.Hidden(old);}}
 [TestCase("amount")][TestCase("type")][TestCase("expiry")]
 public void CurrentLayerFieldAndLifetimeChangesAreObservedWithoutRetainingAStaleMark(string change)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0")){f.Zone.TileState.Clear(20,10);f.Zone.TileState.WriteCoating(20,10,"water",3);f.Refresh();Assert.True(View(f,out var old,out var first));Assert.AreEqual(3,first.Amount);var layer=f.Zone.TileState.Get(20,10).Coatings[0];if(change=="amount")layer.Turns=2;else if(change=="type")layer.Id="oil";else{layer.Turns=1;f.Zone.TileState.Tick();}f.Refresh();bool present=View(f,out var root,out var sample);Assert.AreEqual(change!="expiry",present);if(present){Assert.AreSame(old,root);Assert.AreEqual(change=="type"?"coating:oil":"coating:water",sample.Kind);Assert.AreEqual(change=="amount"?2:3,sample.Amount);}else SpawnRing3DIntegrationFixture.Hidden(old);}}
 [TestCase("oil","coating:oil")][TestCase("ice","coating:ice")][TestCase("petals","residue:petals")]
 public void HigherPriorityNativeLayerCannotBorrowUnderlyingEnergy(string add,string expected)
 {using(var f=new SpawnRing3DIntegrationFixture("Overworld.12.10.0")){f.Zone.TileState.Clear(20,10);f.Zone.TileState.WriteCoating(20,10,"water",3);if(add=="petals")f.Zone.TileState.WriteResidue(20,10,add,2);else f.Zone.TileState.WriteCoating(20,10,add,2);f.Zone.TileState.AddCharge(20,10,2);f.Refresh();Assert.True(View(f,out _,out var s));Assert.AreEqual(expected,s.Kind);}}
}}
