using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;using System.Reflection;
using CavesOfOoo.Core;using CavesOfOoo.Data;using CavesOfOoo.Rendering;using NUnit.Framework;using UnityEngine;
namespace CavesOfOoo.Tests{public sealed class SpreadSurfaceMarkSourceTests{
 OverworldZoneManager manager;Zone zone;Dictionary<string,LiquidDefinition> prior;bool oldInit;IList reactions;object[] oldReactions;bool oldReactionInit;
 static FieldInfo Map=>typeof(LiquidRegistry).GetField("_byId",BindingFlags.NonPublic|BindingFlags.Static);static FieldInfo Init=>typeof(LiquidRegistry).GetField("_initialized",BindingFlags.NonPublic|BindingFlags.Static);
 [SetUp]public void Setup(){prior=new Dictionary<string,LiquidDefinition>((Dictionary<string,LiquidDefinition>)Map.GetValue(null));oldInit=LiquidRegistry.IsInitialized;LiquidRegistry.InitializeFromJsonSources(Directory.GetFiles(Path.Combine(Application.dataPath,"Resources/Content/Data/LiquidDefinitions"),"*.json").Select(File.ReadAllText));reactions=(IList)typeof(TileReactionSystem).GetField("_reactions",BindingFlags.NonPublic|BindingFlags.Static).GetValue(null);oldReactions=reactions.Cast<object>().ToArray();oldReactionInit=TileReactionSystem.IsInitialized;TileReactionSystem.Initialize(File.ReadAllText(Path.Combine(Application.dataPath,"Resources/Content/Data/TileReactions/Reactions.json")));manager=OverworldZoneManager.CreateDetached(new EntityFactory(),64);manager.WorldMap.Tiles[4,9]=BiomeType.Spread;manager.WorldMap.SetPOI(4,9,null);zone=new Zone("Overworld.4.9.0");manager.SetActiveZone(zone);foreach(var c in zone.Cells){c.Explored=true;c.IsVisible=true;}}
 [TearDown]public void Clean(){var map=(Dictionary<string,LiquidDefinition>)Map.GetValue(null);map.Clear();foreach(var p in prior)map.Add(p.Key,p.Value);Init.SetValue(null,oldInit);reactions.Clear();foreach(var r in oldReactions)reactions.Add(r);typeof(TileReactionSystem).GetField("<IsInitialized>k__BackingField",BindingFlags.NonPublic|BindingFlags.Static).SetValue(null,oldReactionInit);}
 [TestCase("acid")][TestCase("bog-mire")][TestCase("bower-resin-amber")][TestCase("brine")][TestCase("carapace-ichor")][TestCase("choir-mirror-mucilage")][TestCase("choir-wort")][TestCase("convalessence")][TestCase("felling-counter-resin")][TestCase("gel")][TestCase("held-breath-lacquer")][TestCase("honey")][TestCase("ice")][TestCase("iron-gall-ink")][TestCase("lantern-beetle-ichor")][TestCase("lava")][TestCase("lumen-slime")][TestCase("memory-bath")][TestCase("oil")][TestCase("pebble-sundew-dew")][TestCase("pitch")][TestCase("sap")][TestCase("sundew-mucilage")][TestCase("tepuibone-slurry")][TestCase("veined-pulse-mycelium")][TestCase("water")]
 public void EveryCurrentRegisteredLiquidKeepsItsExactCoatingIdentity(string id){Assert.NotNull(LiquidRegistry.Get(id));zone.TileState.WriteCoating(20,10,id,3);string before=zone.TileState.ToSaveString();Assert.True(SpreadTransientSource.TrySurfaceMark(zone,20,10,out var s));Assert.AreEqual("coating:"+id,s.Kind);Assert.AreEqual(3,s.Amount);Assert.AreEqual(before,zone.TileState.ToSaveString());}
 [TestCase("embers")][TestCase("petals")]public void BothAuthoredResiduesKeepNativePriorityAboveOtherState(string id){zone.TileState.WriteResidue(20,10,id,4);zone.TileState.WriteCoating(20,10,"oil",3);zone.TileState.AddCharge(20,10,2);zone.TileState.WriteCloud(20,10,"smoke",3);Assert.True(SpreadTransientSource.TrySurfaceMark(zone,20,10,out var s));Assert.AreEqual("residue:"+id,s.Kind);Assert.AreEqual(4,s.Amount);}
 [TestCase(false)][TestCase(true)]public void ActualOilReactionChoosesEmbersWhileWaterReactionKeepsSteam(bool oil){zone.TileState.WriteCoating(20,10,oil?"oil":"water",3);zone.TileState.AddHeat(20,10,1);Assert.AreEqual(1,TileReactionSystem.ResolveZone(zone));string before=zone.TileState.ToSaveString();Assert.AreEqual(oil,SpreadTransientSource.TrySurfaceMark(zone,20,10,out var s));if(oil){Assert.AreEqual("residue:embers",s.Kind);Assert.AreEqual("smoke",zone.TileState.Cloud(20,10));Assert.False(SpreadTransientSource.TryElement(zone,20,10,out _));}else{Assert.True(SpreadTransientSource.TryElement(zone,20,10,out s));Assert.AreEqual("steam",s.Kind);}Assert.AreEqual(before,zone.TileState.ToSaveString());}
 [TestCase(false)][TestCase(true)]public void OnlyActualRepresentedSinglePermanentWaterSuppressesItsSurfaceMark(bool represented){zone.TileState.WriteCoating(20,10,"water",ZoneTileState.Permanent);zone.TileState.AddCharge(20,10,1);Assert.AreEqual(!represented,SpreadTransientSource.TrySurfaceMark(zone,20,10,out _,represented));Assert.AreEqual(represented,SpreadTransientSource.TryElement(zone,20,10,out _,represented));}
 [TestCase("oil","coating:oil")][TestCase("ice","coating:ice")][TestCase("water","coating:water")]public void MixedLayerPriorityMatchesCurrentDisplay(string add,string expected){zone.TileState.WriteCoating(20,10,"water",3);zone.TileState.WriteCoating(20,10,add,4);Assert.True(SpreadTransientSource.TrySurfaceMark(zone,20,10,out var s,true));Assert.AreEqual(expected,s.Kind);}
 [TestCase("unknown-residue")][TestCase("unknown-coating")][TestCase("expired")][TestCase("hidden")][TestCase("foreign")][TestCase("detached")]
 public void UnsupportedOrInvisibleSourceCannotClaimKnownGeometry(string fault){zone.TileState.WriteCoating(20,10,"water",3);if(fault=="unknown-residue")zone.TileState.WriteResidue(20,10,"alien",3);else if(fault=="unknown-coating"){zone.TileState.Clear(20,10);zone.TileState.WriteCoating(20,10,"alien",3);}else if(fault=="expired")zone.TileState.Get(20,10).Coatings[0].Turns=0;else if(fault=="hidden")zone.GetCell(20,10).IsVisible=false;else if(fault=="foreign")manager.WorldMap.Tiles[4,9]=BiomeType.Sodden;else zone=new Zone(zone.ZoneID);Assert.False(SpreadTransientSource.TrySurfaceMark(zone,20,10,out _));}
}}
