using System;
using System.Linq;
using CavesOfOoo.Core;
using CavesOfOoo.Rendering;
using NUnit.Framework;
namespace CavesOfOoo.Tests {
public sealed class SpreadPortableRecipesTests {
private DensityLootTestScope scope;
[SetUp] public void Setup(){scope=new DensityLootTestScope();}
[TearDown] public void TearDown(){scope.Dispose();}
[TestCase("Bone")]
[TestCase("GoldCoin")]
[TestCase("InkVial")]
[TestCase("Dagger")]
[TestCase("Starapple")]
[TestCase("HealingTonic")]
[TestCase("PoisonTonic")]
[TestCase("FireTonic")]
[TestCase("ForgedWeapon")]
[TestCase("SteelBladeComponent")]
[TestCase("IronSpikeComponent")]
[TestCase("OakHaftComponent")]
[TestCase("WillowHaftComponent")]
[TestCase("LeatherBindingComponent")]
[TestCase("SerratedEdgeComponent")]
[TestCase("FireMoss")]
[TestCase("LampOil")]
[TestCase("EmberFruit")]
[TestCase("FrostLichen")]
[TestCase("GlacierSalt")]
[TestCase("GlimmerBrine")]
[TestCase("SparkRoot")]
[TestCase("VenomGland")]
[TestCase("BogSap")]
[TestCase("CandyHeartRoot")]
[TestCase("MendleafSprig")]
[TestCase("StoneburrSeed")]
[TestCase("BlastcapSpore")]
[TestCase("CandyCarrotSeed")]
[TestCase("EmberwheatSeed")]
[TestCase("CandyCarrot")]
[TestCase("WateringGrimoire")]
[TestCase("Emberwheat")]
[TestCase("BrewedTonic")]
[TestCase("InertSludge")]
[TestCase("AcidTonic")]
[TestCase("LightningTonic")]
[TestCase("FrostTonic")]
[TestCase("WaterTonic")]
[TestCase("BleedTonic")]
[TestCase("CharredTonic")]
[TestCase("Antidote")]
[TestCase("BurnSalve")]
[TestCase("Panacea")]
[TestCase("LeatherArmor")]
[TestCase("ChainMail")]
[TestCase("LongSword")]
[TestCase("Battleaxe")]
[TestCase("Greatsword")]
[TestCase("ShortSword")]
[TestCase("Mace")]
[TestCase("Spear")]
[TestCase("Hatchet")]
[TestCase("Claymore")]
[TestCase("Cudgel")]
[TestCase("Buckler")]
[TestCase("IronHelmet")]
[TestCase("LeatherBoots")]
[TestCase("LeatherGloves")]
[TestCase("LeatherCap")]
[TestCase("IronshodBoots")]
[TestCase("WardedCloak")]
[TestCase("IronBuckler")]
[TestCase("PlateArmor")]
[TestCase("Cloak")]
[TestCase("SpeedTonic")]
[TestCase("StrengthTonic")]
[TestCase("StoneskinTonic")]
[TestCase("Mushroom")]
[TestCase("DriedMeat")]
[TestCase("LoanerDagger")]
[TestCase("LoanerSpear")]
[TestCase("LoanerLongsword")]
[TestCase("Warhammer")]
[TestCase("ChoirSpine")]
[TestCase("OldWorldPipe")]
[TestCase("Sporeblade")]
[TestCase("FlamingSword")]
[TestCase("IceSword")]
[TestCase("CryoLance")]
[TestCase("EmberSpear")]
[TestCase("AcidicDagger")]
[TestCase("VenomDagger")]
[TestCase("ThunderHammer")]
[TestCase("EchoKnife")]
[TestCase("TemporalShard")]
[TestCase("SeveranceEdge")]
[TestCase("GlassblownStiletto")]
[TestCase("DissolutionMaul")]
[TestCase("FirstRootGlaive")]
[TestCase("PalimpsestBlade")]
[TestCase("LanternOil")]
[TestCase("RawMeat")]
[TestCase("CookedMeat")]
[TestCase("RoastedStarapple")]
[TestCase("Torch")]
[TestCase("SilverSand")]
[TestCase("WellMaintenanceManual")]
[TestCase("PurifyWaterGrimoire")]
[TestCase("GrimoireCopy")]
[TestCase("RiteGrimoire")]
[TestCase("MendingRiteGrimoire")]
[TestCase("OvenBuildersGuide")]
[TestCase("FireClay")]
[TestCase("KindleRiteGrimoire")]
[TestCase("KindleGrimoire")]
[TestCase("QuenchGrimoire")]
[TestCase("ConflagrationGrimoire")]
[TestCase("IceLanceGrimoire")]
[TestCase("AcidSprayGrimoire")]
[TestCase("ArcBoltGrimoire")]
[TestCase("RimeNovaGrimoire")]
[TestCase("ThunderclapGrimoire")]
[TestCase("EmberVeinGrimoire")]
[TestCase("KindleFlameGrimoire")]
[TestCase("DryingBreezeGrimoire")]
[TestCase("HearthwarmGrimoire")]
[TestCase("ConjureWaterGrimoire")]
[TestCase("ChillDraftGrimoire")]
[TestCase("WardGleamGrimoire")]
[TestCase("SchematicHonedEdge")]
[TestCase("SchematicReinforcedPlating")]
[TestCase("SchematicDuelistCut")]
[TestCase("LanternOilRecipe")]
[TestCase("WardOil")]
[TestCase("PaleSalt")]
[TestCase("ChoirIron")]
[TestCase("WildBerries")]
[TestCase("Honeycomb")]
[TestCase("GlowQuartz")]
[TestCase("PoisonGasGrenade")]
[TestCase("SleepGasGrenade")]
[TestCase("StunGasGrenade")]
[TestCase("StormAnvilGrimoire")]
[TestCase("HangingBoltGrimoire")]
[TestCase("RenderedSteamGrimoire")]
[TestCase("ScaldingVeilGrimoire")]
[TestCase("FulminationGrimoire")]
[TestCase("ShatteredRimeGrimoire")]
[TestCase("StillHeartGrimoire")]
[TestCase("VerdigrisBloomGrimoire")]
[TestCase("HollowCoinGrimoire")]
[TestCase("SunderingWordGrimoire")]
[TestCase("BloodletterLedgerGrimoire")]
[TestCase("SaltbriarSprig")]
[TestCase("WovenDoll")]
[TestCase("GroveRed")]
[TestCase("ShamblerSporeSac")]
[TestCase("Tepuibone")]
[TestCase("PruningWrit")]
[TestCase("BreacherCleaver")]
[TestCase("IronKey")]
[TestCase("StillleafKey")]
[TestCase("StillleafRegister")]
[TestCase("FrogOil")]
[TestCase("SealedBogTakenBody")]
[TestCase("MemoryMarble")]
[TestCase("MuteStone")]
[TestCase("ChoirCutting")]
[TestCase("Waterskin")]
[TestCase("RoastedMushroom")]
[TestCase("TemperedLongSword")]
[TestCase("CounterweightMaul")]
[TestCase("FineRingMail")]
[TestCase("RivetedPlate")]
[TestCase("LiquidFlask")]
[TestCase("Codex01")]
[TestCase("Codex02")]
[TestCase("Codex03")]
[TestCase("Codex04")]
[TestCase("Codex05")]
[TestCase("Codex06")]
[TestCase("Codex07")]
[TestCase("Codex08")]
[TestCase("Codex09")]
[TestCase("Codex10")]
[TestCase("Codex11")]
[TestCase("Codex12")]
[TestCase("Codex13")]
public void ActualConcretePortableHasExactDistinctRecipe(string name){var item=scope.Factory.CreateEntity(name);Assert.True(SpreadPortableRecipes.TryRecipe(item,out string id),name);Assert.AreEqual("spread-portable-"+name.ToLowerInvariant(),id);}
[TestCase("Item")][TestCase("MeleeWeapon")][TestCase("FoodItem")][TestCase("TonicItem")][TestCase("WeaponComponentItem")][TestCase("ReagentItem")][TestCase("ArmorItem")][TestCase("Player")][TestCase("MarlbackScrabbler")]
public void AbstractOrCreatureCannotBecomeAnItem(string name){Assert.False(SpreadPortableRecipes.TryRecipe(scope.Factory.CreateEntity(name),out _));}
[TestCase("WarlordCleaver")][TestCase("UnknownItem")][TestCase("dagger")][TestCase("Dagger/Other")]
public void ForgedNameCannotSelectExistingArt(string name){var item=scope.Factory.CreateEntity("Dagger");item.BlueprintName=name;Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[Test]public void NullRefuses(){Assert.False(SpreadPortableRecipes.TryRecipe(null,out _));}
[TestCase("natural")][TestCase("creature")][TestCase("hidden")][TestCase("untakeable")][TestCase("foreignPhysics")][TestCase("foreignRender")][TestCase("visualOverride")][TestCase("variantOverride")]
public void CurrentIdentityRefusalsAreNotGlyphFallback(string change){var item=scope.Factory.CreateEntity("Dagger");var p=item.GetPart<PhysicsPart>();var r=item.GetPart<RenderPart>();switch(change){case "natural":item.SetTag("Natural");break;case "creature":item.SetTag("Creature");break;case "hidden":r.Visible=false;break;case "untakeable":p.Takeable=false;break;case "foreignPhysics":p.ParentEntity=new Entity();break;case "foreignRender":r.ParentEntity=new Entity();break;case "visualOverride":r.VisualID="foreign";break;case "variantOverride":r.VisualVariant="foreign";break;}Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[Test]public void RecipeQueryNeverMovesStockOrChangesItem(){var zone=new Zone("portable");var item=scope.Factory.CreateEntity("Dagger");zone.AddEntity(item,4,6);var inventory=scope.Factory.CreateEntity("Player").GetPart<InventoryPart>();string id=item.ID;Assert.True(SpreadPortableRecipes.TryRecipe(item,out _));Assert.AreSame(item,zone.GetCell(4,6).Objects.Single());Assert.AreEqual(id,item.ID);Assert.IsNull(item.GetPart<PhysicsPart>().InInventory);Assert.IsNull(item.GetPart<PhysicsPart>().Equipped);}
[TestCase("CreatureCorpse")][TestCase("MarlbackCorpse")]
public void UnprovenCorpseDoesNotClaimSpecies(string name){Assert.False(SpreadPortableRecipes.TryRecipe(scope.Factory.CreateEntity(name),out _));}
[TestCase(-1,3)][TestCase(4,3)][TestCase(0,0)]public void MalformedWaterskinRefuses(int charges,int cap){var item=scope.Factory.CreateEntity("Waterskin");item.GetPart<WaterskinPart>().Charges=charges;item.GetPart<WaterskinPart>().Capacity=cap;Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
[TestCase(-1,12,"")][TestCase(13,12,"Water")][TestCase(1,0,"Water")][TestCase(1,12,"")][TestCase(0,12,"Water")][TestCase(1,12,"MissingLiquid")]
public void MalformedFlaskRefuses(int volume,int cap,string liquid){var item=scope.Factory.CreateEntity("LiquidFlask");var v=item.GetPart<LiquidVesselPart>();v.Volume=volume;v.Capacity=cap;v.LiquidId=liquid;Assert.False(SpreadPortableRecipes.TryRecipe(item,out _));}
} }
