#!/usr/bin/env python3
"""Write exact source-image/native/3D reconciliation, without changing gameplay."""
import json,math,sys,hashlib
from pathlib import Path
source=Path(__file__).resolve().parent
out=Path(sys.argv[1]).resolve()
n=json.loads((source/'native-definition.json').read_text());a=json.loads((source/'art-definition.json').read_text());m=json.loads((out/'manifest.json').read_text())
ni={o['id']:o for o in n['owners']};ai={o['id']:o for o in a['owners']};mi={o['ownerId']:o for o in m['owners']};ar={r['id']:r for r in a['rooms']}
water=[{'x':c['x'],'y':c['y']} for c in n['cells'] if c['water']]
def v3(x,y,z):return {'x':round(x,5),'y':round(y,5),'z':round(z,5)}
def cellcentre(x,y):return v3(x+.5,0,25-y-.5)
rooms=[]
for b in n['buildings']:
 xs=[p['x'] for p in b['interior']];ys=[p['y'] for p in b['interior']]
 x0=min(xs)-.46;x1=max(xs)+1.46;z0=25-max(ys)-1.46;z1=25-min(ys)+.46
 poly=ar[b['id']]['interiorPolygon']
 rooms.append({'id':b['id'],'interiorCells':b['interior'],'nativeInteriorBoundsInclusive':{'minX':min(xs),'maxX':max(xs),'minY':min(ys),'maxY':max(ys)},'doorOwnerId':b['doorId'],'doorCell':{'x':ni[b['doorId']]['anchorX'],'y':ni[b['doorId']]['anchorY']},'doorHingeWorld':mi[b['doorId']]['position'],'nativeEntryCell':{'x':b['entryX'],'y':b['entryY']},'shellExteriorXZ':{'minX':x0,'maxX':x1,'minZ':z0,'maxZ':z1},'sourceImageInteriorPolygonPixels':poly,'reconciliation':'Rectangular physical room follows the shipped interior cell set; screenshot polygon is reference evidence, not a new movement boundary. South-facing doorway follows the native door cell, even when its rendered centre differs from reference pixels.'})
rows=[]
for oid,o in ni.items():
 arto=ai[oid];p=mi[oid];foot=arto.get('sourceFoot')
 row={'ownerId':oid,'kind':o['kind'],'roomId':o.get('roomId'),'nativeAnchor':{'x':o['anchorX'],'y':o['anchorY']},'nativeCellCentreUnity':cellcentre(o['anchorX'],o['anchorY']),'nativeFootprint':o['footprint'],'nativeBridgeSupport':o.get('bridgeSupport',[]),'nativeBlocksMovement':o['blocksMovement'],'sourceImageFootPixels':foot,'modelId':p['modelId'],'modelOriginUnity':p['position'],'modelOffsetUnity':p['visualOffset'],'modelScale':p['scale'],'rotationY':p['rotationY'],'visibility':p['visibleWhen']}
 if foot:row['sourceImageFootProjectedUnity']=v3(n['originX']+foot[0]/n['pixelsPerCell'],0,25-foot[1]/n['pixelsPerCell'])
 row['offsetPurpose']='Owner cell centre is model origin.'
 if o['kind'] in ('building-shell','roof'):row['offsetPurpose']='Native owner anchor is the model root; asymmetric local shell/roof bounds span native room cells.'
 elif o['kind']=='door':row['offsetPurpose']='Left hinge is .45 units west of native door centre; visual leaf spans the doorway.'
 elif any(abs(v)>1e-8 for v in p['visualOffset'].values()):row['offsetPurpose']='Visual model centre is offset from the native foot/interaction anchor to fit the native multi-cell fixture. The offset moves with the owner; it does not move any native footprint.'
 rows.append(row)
report={'schemaVersion':1,'id':'morrowfast-village3d-layout-reconciliation','authoritativeGeometry':'Existing native Morrowfast definition and owner IDs. The screenshot guides appearance, not collision or save identity.','nativeDefinitionSha256':hashlib.sha256((source/'native-definition.json').read_bytes()).hexdigest(),'artDefinitionSha256':hashlib.sha256((source/'art-definition.json').read_bytes()).hexdigest(),'coordinates':m['coordinates'],'composition':{'referenceArtX':[21.25,58.75],'referenceArtZ':[0,25],'renderCameraXZ':[40,12.5],'orthographicWidth':37.5,'groundXZ':[0,80,0,25],'groundExtensionReason':'The game camera may follow the actor outside the reference crop. Full native 80x25 ground coverage prevents a void.','uiExcluded':'Reference black sidebar, text log, status and hotbar are supplied by native UI, never model geometry.'},'deliberateDifferences':[{'id':'native-west-creek','description':'The reference shows a western cobbled branch without a large obvious creek; the shipped native map contains water there. All 67 native water cells remain water, rendered as a teal channel with shore detail and the native bridge.'},{'id':'native-room-extents','description':'Five shells/roofs use the shipped native interior rectangles and doors. Their image-space size and spacing differ from the screenshot polygons, especially the larger guesthouse and archive.'},{'id':'interiors-authored','description':'The reference depicts roofs. Beds, work surfaces, shelves, storage and hearths beneath them are authored views of existing room owners, not inferred new gameplay.'},{'id':'vegetation-and-gardens','description':'Additional fences, shrubs, rocks and planters are static scenery only. They have no native loot, collision, watering, destruction or persistence semantics.'},{'id':'source-style','description':'Reusable low-poly rounded geometry, a 64-swatch atlas, studio shadows and compact variation families approximate the reference. No screenshot plane or photoreal texture/AO bake is used.'},{'id':'preview-player','description':'The showcase hooded player exists only in the Blender composition, is omitted from persistent owner placements, and must be replaced by the live player view in Unity.'}],'water':{'count':len(water),'cells':water,'nativeBridgeOwners':[o['id'] for o in n['owners'] if o['kind']=='bridge'],'worldBoundsXZ':{'minX':min(c['x'] for c in water),'maxX':max(c['x'] for c in water)+1,'minZ':25-max(c['y'] for c in water)-1,'maxZ':25-min(c['y'] for c in water)}},'buildings':rooms,'owners':rows,'staticPlacements':m['staticPlacements'],'acceptanceStatus':'This ledger proves correspondence to source definitions only. Actual Unity materials, axis conversion, visibility, interaction and performance require integration tests and live review.'}
report['starterGarden']={'cells':m.get('starterGardenCells',[]),'nativeStartCell':{'x':40,'y':23},'artModel':'detail-patch-04-00','representation':'Bare inset soil and shallow furrows only; no preplanted crops. Native Plantable/growth/inventory state remains gameplay-owned.','roadAdjustment':'Cosmetic paving/scatter is excluded from X41/X42,Y21..23 to create the right-hand verge garden. X40 main road remains clear; existing 71 owners, room footprints and creek geometry remain unchanged.'}
report['deliberateDifferences'].append({'id':'authorized-starting-garden','description':'User-authorized village new-game start adds six real native Plantable cells at X41/X42,Y21..23, visualized as bare inset earth in an existing terrain-detail mesh. The reference image has no such starting plot; no crops or new art owners are invented. Cosmetic right-verge paving is trimmed around the exact cells while the X40 road stays clear.'})
(out/'reports/layout-reconciliation.json').write_text(json.dumps(report,indent=2)+'\n')
text=['# Village layout reconciliation','',report['authoritativeGeometry'],'',f"All {len(rows)} native owner IDs are represented. Ground covers 80 by 25 cells; the reference composition occupies X 21.25–58.75 and Z 0–25.",'','## Deliberate image differences','']
for d in report['deliberateDifferences']:text+=['- **'+d['id']+'**: '+d['description']]
text+=['','## Exact room placement','','| Room | Native interior cells | Door cell | Entry cell | Shell X bounds | Shell Z bounds |','|---|---|---|---|---|---|']
for r in rooms:
 b=r['nativeInteriorBoundsInclusive'];e=r['shellExteriorXZ'];d=r['doorCell'];en=r['nativeEntryCell']
 text.append(f"| {r['id']} | X {b['minX']}–{b['maxX']}, Y {b['minY']}–{b['maxY']} | ({d['x']}, {d['y']}) | ({en['x']}, {en['y']}) | {e['minX']:.2f}–{e['maxX']:.2f} | {e['minZ']:.2f}–{e['maxZ']:.2f} |")
text+=['','The companion JSON lists every source image foot, native anchor and footprint, runtime model origin and offset, room visibility, and static placement. Source image feet and model centres are different concepts; their coordinate difference is not automatically an alignment defect.','',report['acceptanceStatus'],'']
(out/'reports/layout-reconciliation.md').write_text('\n'.join(text))
print(json.dumps({'owners':len(rows),'rooms':len(rooms),'waterCells':len(water),'json':str(out/'reports/layout-reconciliation.json')}))
